import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

/// List of categories of UnicodeEmojis
const List<CategoryEmoji> defaultUnicodeEmojiSet = [
// ======================================================= Category.SMILEYS
  CategoryEmoji(Category.SMILEYS, [
    UnicodeEmoji('😀', 'Grinning Face'),
    UnicodeEmoji('😃', 'Grinning Face With Big Eyes'),
    UnicodeEmoji('😄', 'Grinning Face With Smiling Eyes'),
    UnicodeEmoji('😁', 'Beaming Face With Smiling Eyes'),
    UnicodeEmoji('😆', 'Grinning Squinting Face'),
    UnicodeEmoji('😅', 'Grinning Face With Sweat'),
    UnicodeEmoji('🤣', 'Rolling on the Floor Laughing'),
    UnicodeEmoji('😂', 'Face With Tears of Joy'),
    UnicodeEmoji('🙂', 'Slightly Smiling Face'),
    UnicodeEmoji('🙃', 'Upside-Down Face'),
    UnicodeEmoji('😉', 'Winking Face'),
    UnicodeEmoji('😊', 'Smiling Face With Smiling Eyes'),
    UnicodeEmoji('😇', 'Smiling Face With Halo'),
    UnicodeEmoji('🥰', 'Smiling Face With Hearts'),
    UnicodeEmoji('😍', 'Smiling Face With Heart-Eyes'),
    UnicodeEmoji('🤩', 'Star-Struck'),
    UnicodeEmoji('😘', 'Face Blowing a Kiss'),
    UnicodeEmoji('😗', 'Kissing Face'),
    UnicodeEmoji('☺️', 'Smiling Face'),
    UnicodeEmoji('😚', 'Kissing Face With Closed Eyes'),
    UnicodeEmoji('😙', 'Kissing Face With Smiling Eyes'),
    UnicodeEmoji('😋', 'Face Savoring Food'),
    UnicodeEmoji('😛', 'Face With Tongue'),
    UnicodeEmoji('😜', 'Winking Face With Tongue'),
    UnicodeEmoji('🤪', 'Zany Face'),
    UnicodeEmoji('😝', 'Squinting Face With Tongue'),
    UnicodeEmoji('🤑', 'Money-Mouth Face'),
    UnicodeEmoji('🤗', 'Hugging Face'),
    UnicodeEmoji('🫣', 'Face with Peeking Eye'),
    UnicodeEmoji('🤭', 'Face With Hand Over Mouth'),
    UnicodeEmoji('🫢', 'Face with Open Eyes and Hand Over Mouth'),
    UnicodeEmoji('🫡', 'Saluting Face'),
    UnicodeEmoji('🤫', 'Shushing Face'),
    UnicodeEmoji('🫠', 'Melting Face'),
    UnicodeEmoji('🤔', 'Thinking Face'),
    UnicodeEmoji('🤐', 'Zipper-Mouth Face'),
    UnicodeEmoji('🤨', 'Face With Raised Eyebrow'),
    UnicodeEmoji('😐', 'Neutral Face'),
    UnicodeEmoji('🫤', 'Face with Diagonal Mouth'),
    UnicodeEmoji('😑', 'Expressionless Face'),
    UnicodeEmoji('😶', 'Face Without Mouth'),
    UnicodeEmoji('🫥', 'Dotted Line Face'),
    UnicodeEmoji('😏', 'Smirking Face'),
    UnicodeEmoji('😒', 'Unamused Face'),
    UnicodeEmoji('🙄', 'Face With Rolling Eyes'),
    UnicodeEmoji('😬', 'Grimacing Face'),
    UnicodeEmoji('🤥', 'Lying Face'),
    UnicodeEmoji('😌', 'Relieved Face'),
    UnicodeEmoji('😔', 'Pensive Face'),
    UnicodeEmoji('🥹', 'Face Holding Back Tears'),
    UnicodeEmoji('😪', 'Sleepy Face'),
    UnicodeEmoji('🤤', 'Drooling Face'),
    UnicodeEmoji('😴', 'Sleeping Face'),
    UnicodeEmoji('😷', 'Face With Medical Mask'),
    UnicodeEmoji('🤒', 'Face With Thermometer'),
    UnicodeEmoji('🤕', 'Face With Head-Bandage'),
    UnicodeEmoji('🤢', 'Nauseated Face'),
    UnicodeEmoji('🤮', 'Face Vomiting'),
    UnicodeEmoji('🤧', 'Sneezing Face'),
    UnicodeEmoji('🥵', 'Hot Face'),
    UnicodeEmoji('🥶', 'Cold Face'),
    UnicodeEmoji('🥴', 'Woozy Face'),
    UnicodeEmoji('😵', 'Dizzy Face'),
    UnicodeEmoji('🤯', 'Exploding Head'),
    UnicodeEmoji('🤠', 'Cowboy Hat Face'),
    UnicodeEmoji('🥳', 'Partying Face'),
    UnicodeEmoji('😎', 'Smiling Face With Sunglasses'),
    UnicodeEmoji('🤓', 'Nerd Face'),
    UnicodeEmoji('🧐', 'Face With Monocle'),
    UnicodeEmoji('😕', 'Confused Face'),
    UnicodeEmoji('😟', 'Worried Face'),
    UnicodeEmoji('🙁', 'Slightly Frowning Face'),
    UnicodeEmoji('☹️', 'Frowning Face'),
    UnicodeEmoji('😮', 'Face With Open Mouth'),
    UnicodeEmoji('😯', 'Hushed Face'),
    UnicodeEmoji('😲', 'Astonished Face'),
    UnicodeEmoji('😳', 'Flushed Face'),
    UnicodeEmoji('🥺', 'Pleading Face'),
    UnicodeEmoji('😦', 'Frowning Face With Open Mouth'),
    UnicodeEmoji('😧', 'Anguished Face'),
    UnicodeEmoji('😨', 'Fearful Face'),
    UnicodeEmoji('😰', 'Anxious Face With Sweat'),
    UnicodeEmoji('😥', 'Sad but Relieved Face'),
    UnicodeEmoji('😢', 'Crying Face'),
    UnicodeEmoji('😭', 'Loudly Crying Face'),
    UnicodeEmoji('😱', 'Face Screaming in Fear'),
    UnicodeEmoji('😖', 'Confounded Face'),
    UnicodeEmoji('😣', 'Persevering Face'),
    UnicodeEmoji('😞', 'Disappointed Face'),
    UnicodeEmoji('😓', 'Downcast Face With Sweat'),
    UnicodeEmoji('😩', 'Weary Face'),
    UnicodeEmoji('😫', 'Tired Face'),
    UnicodeEmoji('😤', 'Face With Steam From Nose'),
    UnicodeEmoji('😡', 'Pouting Face'),
    UnicodeEmoji('😠', 'Angry Face'),
    UnicodeEmoji('🤬', 'Face With Symbols on Mouth'),
    UnicodeEmoji('😈', 'Smiling Face With Horns'),
    UnicodeEmoji('👿', 'Angry Face With Horns'),
    UnicodeEmoji('💀', 'Skull'),
    UnicodeEmoji('☠️', 'Skull and Crossbones'),
    UnicodeEmoji('💩', 'Pile of Poo'),
    UnicodeEmoji('🤡', 'Clown Face'),
    UnicodeEmoji('👹', 'Ogre'),
    UnicodeEmoji('👺', 'Goblin'),
    UnicodeEmoji('👻', 'Ghost'),
    UnicodeEmoji('👽', 'Alien'),
    UnicodeEmoji('👾', 'Alien Monster'),
    UnicodeEmoji('🤖', 'Robot Face'),
    UnicodeEmoji('🎃', 'Jack-O-Lantern'),
    UnicodeEmoji('😺', 'Grinning Cat Face'),
    UnicodeEmoji('😸', 'Grinning Cat Face With Smiling Eyes'),
    UnicodeEmoji('😹', 'Cat Face With Tears of Joy'),
    UnicodeEmoji('😻', 'Smiling Cat Face With Heart-Eyes'),
    UnicodeEmoji('😼', 'Cat Face With Wry Smile'),
    UnicodeEmoji('😽', 'Kissing Cat Face'),
    UnicodeEmoji('🙀', 'Weary Cat Face'),
    UnicodeEmoji('😿', 'Crying Cat Face'),
    UnicodeEmoji('😾', 'Pouting Cat Face'),
    UnicodeEmoji('🫶', 'Heart Hands', hasSkinTone: true),
    UnicodeEmoji('👋', 'Waving Hand', hasSkinTone: true),
    UnicodeEmoji('🤚', 'Raised Back of Hand', hasSkinTone: true),
    UnicodeEmoji('🖐️', 'Hand With Fingers Splayed', hasSkinTone: true),
    UnicodeEmoji('✋', 'Raised Hand', hasSkinTone: true),
    UnicodeEmoji('🖖', 'Vulcan Salute', hasSkinTone: true),
    UnicodeEmoji('👌', 'OK Hand', hasSkinTone: true),
    UnicodeEmoji('🤌', 'Pinched Fingers', hasSkinTone: true),
    UnicodeEmoji('🤏', 'Pinching Hand', hasSkinTone: true),
    UnicodeEmoji('🫳', 'Palm Down Hand', hasSkinTone: true),
    UnicodeEmoji('🫴', 'Palm Up Hand', hasSkinTone: true),
    UnicodeEmoji('✌️', 'Victory Hand', hasSkinTone: true),
    UnicodeEmoji(
      '🫰',
      'Hand with Index Finger and Thumb Crossed',
      hasSkinTone: true,
    ),
    UnicodeEmoji('🤞', 'Crossed Fingers', hasSkinTone: true),
    UnicodeEmoji('🤟', 'Love-You Gesture', hasSkinTone: true),
    UnicodeEmoji('🤘', 'Sign of the Horns', hasSkinTone: true),
    UnicodeEmoji('🤙', 'Call Me Hand', hasSkinTone: true),
    UnicodeEmoji('👈', 'Backhand Index Pointing Left', hasSkinTone: true),
    UnicodeEmoji('👉', 'Backhand Index Pointing Right', hasSkinTone: true),
    UnicodeEmoji('👆', 'Backhand Index Pointing Up', hasSkinTone: true),
    UnicodeEmoji('🖕', 'Middle Finger', hasSkinTone: true),
    UnicodeEmoji('👇', 'Backhand Index Pointing Down', hasSkinTone: true),
    UnicodeEmoji('☝️', 'Index Pointing Up', hasSkinTone: true),
    UnicodeEmoji('👍', 'Thumbs Up', hasSkinTone: true),
    UnicodeEmoji('👎', 'Thumbs Down', hasSkinTone: true),
    UnicodeEmoji('✊', 'Raised Fist', hasSkinTone: true),
    UnicodeEmoji('👊', 'Oncoming Fist', hasSkinTone: true),
    UnicodeEmoji('🤛', 'Left-Facing Fist', hasSkinTone: true),
    UnicodeEmoji('🤜', 'Right-Facing Fist', hasSkinTone: true),
    UnicodeEmoji('🫲', 'Leftwards Hand', hasSkinTone: true),
    UnicodeEmoji('🫱', 'Rightwards Hand', hasSkinTone: true),
    UnicodeEmoji('👏', 'Clapping Hands', hasSkinTone: true),
    UnicodeEmoji('🙌', 'Raising Hands', hasSkinTone: true),
    UnicodeEmoji('👐', 'Open Hands', hasSkinTone: true),
    UnicodeEmoji('🤲', 'Palms Up Together', hasSkinTone: true),
    UnicodeEmoji('🤝', 'Handshake', hasSkinTone: true),
    UnicodeEmoji('🙏', 'Folded Hands', hasSkinTone: true),
    UnicodeEmoji('🫵', 'Index Pointing at the Viewer', hasSkinTone: true),
    UnicodeEmoji('✍️', 'Writing Hand', hasSkinTone: true),
    UnicodeEmoji('💅', 'Nail Polish', hasSkinTone: true),
    UnicodeEmoji('🤳', 'Selfie', hasSkinTone: true),
    UnicodeEmoji('💪', 'Flexed Biceps', hasSkinTone: true),
    UnicodeEmoji('🦵', 'Leg', hasSkinTone: true),
    UnicodeEmoji('🦶', 'Foot', hasSkinTone: true),
    UnicodeEmoji('👂', 'Ear', hasSkinTone: true),
    UnicodeEmoji('👃', 'Nose', hasSkinTone: true),
    UnicodeEmoji('🧠', 'Brain'),
    UnicodeEmoji('🦴', 'Bone'),
    UnicodeEmoji('👀', 'Eyes'),
    UnicodeEmoji('👁️', 'Eye'),
    UnicodeEmoji('💋', 'Kiss Mark'),
    UnicodeEmoji('👄', 'Mouth'),
    UnicodeEmoji('🫦', 'Biting Lip'),
    UnicodeEmoji('🦷', 'Tooth'),
    UnicodeEmoji('👅', 'Tongue'),
    UnicodeEmoji('👶', 'Baby', hasSkinTone: true),
    UnicodeEmoji('🧒', 'Child', hasSkinTone: true),
    UnicodeEmoji('👦', 'Boy', hasSkinTone: true),
    UnicodeEmoji('👧', 'Girl', hasSkinTone: true),
    UnicodeEmoji('🧑', 'Person', hasSkinTone: true),
    UnicodeEmoji('👨', 'Man', hasSkinTone: true),
    UnicodeEmoji('🧔', 'Man: Beard', hasSkinTone: true),
    UnicodeEmoji('👱', 'Man: Blond Hair', hasSkinTone: true),
    UnicodeEmoji('👨‍🦰', 'Man: Red Hair', hasSkinTone: true),
    UnicodeEmoji('👨‍🦱', 'Man: Curly Hair', hasSkinTone: true),
    UnicodeEmoji('👨‍🦳', 'Man: White Hair', hasSkinTone: true),
    UnicodeEmoji('👨‍🦲', 'Man: Bald', hasSkinTone: true),
    UnicodeEmoji('👩', 'Woman', hasSkinTone: true),
    UnicodeEmoji('👱‍♀️', 'Woman: Blond Hair', hasSkinTone: true),
    UnicodeEmoji('👩‍🦰', 'Woman: Red Hair', hasSkinTone: true),
    UnicodeEmoji('👩‍🦱', 'Woman: Curly Hair', hasSkinTone: true),
    UnicodeEmoji('👩‍🦳', 'Woman: White Hair', hasSkinTone: true),
    UnicodeEmoji('👩‍🦲', 'Woman: Bald', hasSkinTone: true),
    UnicodeEmoji('🧓', 'Older Person', hasSkinTone: true),
    UnicodeEmoji('👴', 'Old Man', hasSkinTone: true),
    UnicodeEmoji('👵', 'Old Woman', hasSkinTone: true),
    UnicodeEmoji('🙍‍♂️', 'Man Frowning', hasSkinTone: true),
    UnicodeEmoji('🙍‍♀️', 'Woman Frowning', hasSkinTone: true),
    UnicodeEmoji('🙎‍♂️', 'Man Pouting', hasSkinTone: true),
    UnicodeEmoji('🙎‍♀️', 'Woman Pouting', hasSkinTone: true),
    UnicodeEmoji('🙅‍♂️', 'Man Gesturing No', hasSkinTone: true),
    UnicodeEmoji('🙅‍♀️', 'Woman Gesturing No', hasSkinTone: true),
    UnicodeEmoji('🙆‍♂️', 'Man Gesturing OK', hasSkinTone: true),
    UnicodeEmoji('🙆‍♀️', 'Woman Gesturing OK', hasSkinTone: true),
    UnicodeEmoji('💁‍♂️', 'Man Tipping Hand', hasSkinTone: true),
    UnicodeEmoji('💁‍♀️', 'Woman Tipping Hand', hasSkinTone: true),
    UnicodeEmoji('🙋‍♂️', 'Man Raising Hand', hasSkinTone: true),
    UnicodeEmoji('🙋‍♀️', 'Woman Raising Hand', hasSkinTone: true),
    UnicodeEmoji('🙇‍♂️', 'Man Bowing', hasSkinTone: true),
    UnicodeEmoji('🙇‍♀️', 'Woman Bowing', hasSkinTone: true),
    UnicodeEmoji('🤦‍♂️', 'Man Facepalming', hasSkinTone: true),
    UnicodeEmoji('🤦‍♀️', 'Woman Facepalming', hasSkinTone: true),
    UnicodeEmoji('🤷‍♂️', 'Man Shrugging', hasSkinTone: true),
    UnicodeEmoji('🤷‍♀️', 'Woman Shrugging', hasSkinTone: true),
    UnicodeEmoji('👨‍⚕️', 'Man Health Worker', hasSkinTone: true),
    UnicodeEmoji('👩‍⚕️', 'Woman Health Worker', hasSkinTone: true),
    UnicodeEmoji('👨‍🎓', 'Man Student', hasSkinTone: true),
    UnicodeEmoji('👩‍🎓', 'Woman Student', hasSkinTone: true),
    UnicodeEmoji('👨‍🏫', 'Man Teacher', hasSkinTone: true),
    UnicodeEmoji('👩‍🏫', 'Woman Teacher', hasSkinTone: true),
    UnicodeEmoji('👨‍⚖️', 'Man Judge', hasSkinTone: true),
    UnicodeEmoji('👩‍⚖️', 'Woman Judge', hasSkinTone: true),
    UnicodeEmoji('👨‍🌾', 'Man Farmer', hasSkinTone: true),
    UnicodeEmoji('👩‍🌾', 'Woman Farmer', hasSkinTone: true),
    UnicodeEmoji('👨‍🍳', 'Man Cook', hasSkinTone: true),
    UnicodeEmoji('👩‍🍳', 'Woman Cook', hasSkinTone: true),
    UnicodeEmoji('👨‍🔧', 'Man Mechanic', hasSkinTone: true),
    UnicodeEmoji('👩‍🔧', 'Woman Mechanic', hasSkinTone: true),
    UnicodeEmoji('👨‍🏭', 'Man Factory Worker', hasSkinTone: true),
    UnicodeEmoji('👩‍🏭', 'Woman Factory Worker', hasSkinTone: true),
    UnicodeEmoji('👨‍💼', 'Man Office Worker', hasSkinTone: true),
    UnicodeEmoji('👩‍💼', 'Woman Office Worker', hasSkinTone: true),
    UnicodeEmoji('👨‍🔬', 'Man Scientist', hasSkinTone: true),
    UnicodeEmoji('👩‍🔬', 'Woman Scientist', hasSkinTone: true),
    UnicodeEmoji('👨‍💻', 'Man Technologist', hasSkinTone: true),
    UnicodeEmoji('👩‍💻', 'Woman Technologist', hasSkinTone: true),
    UnicodeEmoji('👨‍🎤', 'Man Singer', hasSkinTone: true),
    UnicodeEmoji('👩‍🎤', 'Woman Singer', hasSkinTone: true),
    UnicodeEmoji('👨‍🎨', 'Man Artist', hasSkinTone: true),
    UnicodeEmoji('👩‍🎨', 'Woman Artist', hasSkinTone: true),
    UnicodeEmoji('👨‍✈️', 'Man Pilot', hasSkinTone: true),
    UnicodeEmoji('👩‍✈️', 'Woman Pilot', hasSkinTone: true),
    UnicodeEmoji('👨‍🚀', 'Man Astronaut', hasSkinTone: true),
    UnicodeEmoji('👩‍🚀', 'Woman Astronaut', hasSkinTone: true),
    UnicodeEmoji('👨‍🚒', 'Man Firefighter', hasSkinTone: true),
    UnicodeEmoji('👩‍🚒', 'Woman Firefighter', hasSkinTone: true),
    UnicodeEmoji('👮‍♂️', 'Man Police Officer', hasSkinTone: true),
    UnicodeEmoji('👮‍♀️', 'Woman Police Officer', hasSkinTone: true),
    UnicodeEmoji('🕵️‍♂️', 'Man Detective', hasSkinTone: true),
    UnicodeEmoji('🕵️‍♀️', 'Woman Detective', hasSkinTone: true),
    UnicodeEmoji('💂‍♂️', 'Man Guard', hasSkinTone: true),
    UnicodeEmoji('💂‍♀️', 'Woman Guard', hasSkinTone: true),
    UnicodeEmoji('👷‍♂️', 'Man Construction Worker', hasSkinTone: true),
    UnicodeEmoji('👷‍♀️', 'Woman Construction Worker', hasSkinTone: true),
    UnicodeEmoji('🤴', 'Prince', hasSkinTone: true),
    UnicodeEmoji('👸', 'Princess', hasSkinTone: true),
    UnicodeEmoji('👳‍♂️', 'Man Wearing Turban', hasSkinTone: true),
    UnicodeEmoji('👳‍♀️', 'Woman Wearing Turban', hasSkinTone: true),
    UnicodeEmoji('👲', 'Man With Chinese Cap', hasSkinTone: true),
    UnicodeEmoji('🧕', 'Woman With Headscarf', hasSkinTone: true),
    UnicodeEmoji('🤵', 'Man in Tuxedo', hasSkinTone: true),
    UnicodeEmoji('👰', 'Bride With Veil', hasSkinTone: true),
    UnicodeEmoji('🤰', 'Pregnant Woman', hasSkinTone: true),
    UnicodeEmoji('🤱', 'Breast-Feeding', hasSkinTone: true),
    UnicodeEmoji('👼', 'Baby Angel', hasSkinTone: true),
    UnicodeEmoji('🎅', 'Santa Claus', hasSkinTone: true),
    UnicodeEmoji('🤶', 'Mrs. Claus', hasSkinTone: true),
    UnicodeEmoji('🦸‍♂️', 'Man Superhero', hasSkinTone: true),
    UnicodeEmoji('🦸‍♀️', 'Woman Superhero', hasSkinTone: true),
    UnicodeEmoji('🦹‍♂️', 'Man Supervillain', hasSkinTone: true),
    UnicodeEmoji('🦹‍♀️', 'Woman Supervillain', hasSkinTone: true),
    UnicodeEmoji('🧙‍♂️', 'Man Mage', hasSkinTone: true),
    UnicodeEmoji('🧙‍♀️', 'Woman Mage', hasSkinTone: true),
    UnicodeEmoji('🧚‍♂️', 'Man Fairy', hasSkinTone: true),
    UnicodeEmoji('🧚‍♀️', 'Woman Fairy', hasSkinTone: true),
    UnicodeEmoji('🧛‍♂️', 'Man Vampire', hasSkinTone: true),
    UnicodeEmoji('🧛‍♀️', 'Woman Vampire', hasSkinTone: true),
    UnicodeEmoji('🧜‍♂️', 'Merman', hasSkinTone: true),
    UnicodeEmoji('🧜‍♀️', 'Mermaid', hasSkinTone: true),
    UnicodeEmoji('🧝‍♂️', 'Man Elf', hasSkinTone: true),
    UnicodeEmoji('🧝‍♀️', 'Woman Elf', hasSkinTone: true),
    UnicodeEmoji('🧞‍♂️', 'Man Genie'),
    UnicodeEmoji('🧞‍♀️', 'Woman Genie'),
    UnicodeEmoji('🧟‍♂️', 'Man Zombie'),
    UnicodeEmoji('🧟‍♀️', 'Woman Zombie'),
    UnicodeEmoji('💆‍♂️', 'Man Getting Massage', hasSkinTone: true),
    UnicodeEmoji('💆‍♀️', 'Woman Getting Massage', hasSkinTone: true),
    UnicodeEmoji('💇‍♂️', 'Man Getting Haircut', hasSkinTone: true),
    UnicodeEmoji('💇‍♀️', 'Woman Getting Haircut', hasSkinTone: true),
    UnicodeEmoji('🚶‍♂️', 'Man Walking', hasSkinTone: true),
    UnicodeEmoji('🚶‍♀️', 'Woman Walking', hasSkinTone: true),
    UnicodeEmoji('🏃‍♂️', 'Man Running', hasSkinTone: true),
    UnicodeEmoji('🏃‍♀️', 'Woman Running', hasSkinTone: true),
    UnicodeEmoji('🕺', 'Man Dancing', hasSkinTone: true),
    UnicodeEmoji('💃', 'Woman Dancing', hasSkinTone: true),
    UnicodeEmoji('🕴️', 'Man in Suit Levitating', hasSkinTone: true),
    UnicodeEmoji('👯‍♂️', 'Men With Bunny Ears'),
    UnicodeEmoji('👯‍♀️', 'Women With Bunny Ears'),
    UnicodeEmoji('🧖‍♂️', 'Man in Steamy Room', hasSkinTone: true),
    UnicodeEmoji('🧖‍♀️', 'Woman in Steamy Room', hasSkinTone: true),
    UnicodeEmoji('🧘', 'Person in Lotus Position', hasSkinTone: true),
    UnicodeEmoji('👭', 'Women Holding Hands', hasSkinTone: true),
    UnicodeEmoji('👫', 'Woman and Man Holding Hands', hasSkinTone: true),
    UnicodeEmoji('👬', 'Men Holding Hands', hasSkinTone: true),
    UnicodeEmoji('💏', 'Kiss'),
    UnicodeEmoji('👨‍❤️‍💋‍👨', 'Kiss: Man, Man'),
    UnicodeEmoji('👩‍❤️‍💋‍👩', 'Kiss: Woman, Woman'),
    UnicodeEmoji('💑', 'Couple With Heart'),
    UnicodeEmoji('👨‍❤️‍👨', 'Couple With Heart: Man, Man'),
    UnicodeEmoji('👩‍❤️‍👩', 'Couple With Heart: Woman, Woman'),
    UnicodeEmoji('👪', 'Family'),
    UnicodeEmoji('👨‍👩‍👦', 'Family: Man, Woman, Boy'),
    UnicodeEmoji('👨‍👩‍👧', 'Family: Man, Woman, Girl'),
    UnicodeEmoji('👨‍👩‍👧‍👦', 'Family: Man, Woman, Girl, Boy'),
    UnicodeEmoji('👨‍👩‍👦‍👦', 'Family: Man, Woman, Boy, Boy'),
    UnicodeEmoji('👨‍👩‍👧‍👧', 'Family: Man, Woman, Girl, Girl'),
    UnicodeEmoji('👨‍👨‍👦', 'Family: Man, Man, Boy'),
    UnicodeEmoji('👨‍👨‍👧', 'Family: Man, Man, Girl'),
    UnicodeEmoji('👨‍👨‍👧‍👦', 'Family: Man, Man, Girl, Boy'),
    UnicodeEmoji('👨‍👨‍👦‍👦', 'Family: Man, Man, Boy, Boy'),
    UnicodeEmoji('👨‍👨‍👧‍👧', 'Family: Man, Man, Girl, Girl'),
    UnicodeEmoji('👩‍👩‍👦', 'Family: Woman, Woman, Boy'),
    UnicodeEmoji('👩‍👩‍👧', 'Family: Woman, Woman, Girl'),
    UnicodeEmoji('👩‍👩‍👧‍👦', 'Family: Woman, Woman, Girl, Boy'),
    UnicodeEmoji('👩‍👩‍👦‍👦', 'Family: Woman, Woman, Boy, Boy'),
    UnicodeEmoji('👩‍👩‍👧‍👧', 'Family: Woman, Woman, Girl, Girl'),
    UnicodeEmoji('👨‍👦', 'Family: Man, Boy'),
    UnicodeEmoji('👨‍👦‍👦', 'Family: Man, Boy, Boy'),
    UnicodeEmoji('👨‍👧', 'Family: Man, Girl'),
    UnicodeEmoji('👨‍👧‍👦', 'Family: Man, Girl, Boy'),
    UnicodeEmoji('👨‍👧‍👧', 'Family: Man, Girl, Girl'),
    UnicodeEmoji('👩‍👦', 'Family: Woman, Boy'),
    UnicodeEmoji('👩‍👦‍👦', 'Family: Woman, Boy, Boy'),
    UnicodeEmoji('👩‍👧', 'Family: Woman, Girl'),
    UnicodeEmoji('👩‍👧‍👦', 'Family: Woman, Girl, Boy'),
    UnicodeEmoji('👩‍👧‍👧', 'Family: Woman, Girl, Girl'),
    UnicodeEmoji('🗣️', 'Speaking Head'),
    UnicodeEmoji('👤', 'Bust in Silhouette'),
    UnicodeEmoji('👥', 'Busts in Silhouette'),
    UnicodeEmoji('👣', 'Footprints'),
    UnicodeEmoji('🧳', 'Luggage'),
    UnicodeEmoji('🌂', 'Closed Umbrella'),
    UnicodeEmoji('☂️', 'Umbrella'),
    UnicodeEmoji('🧵', 'Thread'),
    UnicodeEmoji('🧶', 'Yarn'),
    UnicodeEmoji('👓', 'Glasses'),
    UnicodeEmoji('🕶️', 'Sunglasses'),
    UnicodeEmoji('🥽', 'Goggles'),
    UnicodeEmoji('🥼', 'Lab Coat'),
    UnicodeEmoji('👔', 'Necktie'),
    UnicodeEmoji('👕', 'T-Shirt'),
    UnicodeEmoji('👖', 'Jeans'),
    UnicodeEmoji('🧣', 'Scarf'),
    UnicodeEmoji('🧤', 'Gloves'),
    UnicodeEmoji('🧥', 'Coat'),
    UnicodeEmoji('🧦', 'Socks'),
    UnicodeEmoji('👗', 'Dress'),
    UnicodeEmoji('👘', 'Kimono'),
    UnicodeEmoji('👙', 'Bikini'),
    UnicodeEmoji('👚', 'Woman’s Clothes'),
    UnicodeEmoji('👛', 'Purse'),
    UnicodeEmoji('👜', 'Handbag'),
    UnicodeEmoji('👝', 'Clutch Bag'),
    UnicodeEmoji('🎒', 'Backpack'),
    UnicodeEmoji('👞', 'Man’s Shoe'),
    UnicodeEmoji('👟', 'Running Shoe'),
    UnicodeEmoji('🥾', 'Hiking Boot'),
    UnicodeEmoji('🥿', 'Flat Shoe'),
    UnicodeEmoji('👠', 'High-Heeled Shoe'),
    UnicodeEmoji('👡', 'Woman’s Sandal'),
    UnicodeEmoji('👢', 'Woman’s Boot'),
    UnicodeEmoji('👑', 'Crown'),
    UnicodeEmoji('👒', 'Woman’s Hat'),
    UnicodeEmoji('🎩', 'Top Hat'),
    UnicodeEmoji('🎓', 'Graduation Cap'),
    UnicodeEmoji('🧢', 'Billed Cap'),
    UnicodeEmoji('⛑️', 'Rescue Worker’s Helmet'),
    UnicodeEmoji('💄', 'Lipstick'),
    UnicodeEmoji('💍', 'Ring'),
    UnicodeEmoji('💼', 'Briefcase')
  ]),

// ======================================================= Category.ANIMALS
  CategoryEmoji(Category.ANIMALS, [
    UnicodeEmoji('🐶', 'Dog Face'),
    UnicodeEmoji('🐱', 'Cat Face'),
    UnicodeEmoji('🐭', 'Mouse Face'),
    UnicodeEmoji('🐹', 'Hamster Face'),
    UnicodeEmoji('🐰', 'Rabbit Face'),
    UnicodeEmoji('🦊', 'Fox Face'),
    UnicodeEmoji('🐻', 'Bear Face'),
    UnicodeEmoji('🐼', 'Panda Face'),
    UnicodeEmoji('🐨', 'Koala Face'),
    UnicodeEmoji('🐯', 'Tiger Face'),
    UnicodeEmoji('🦁', 'Lion Face'),
    UnicodeEmoji('🐮', 'Cow Face'),
    UnicodeEmoji('🐷', 'Pig Face'),
    UnicodeEmoji('🐽', 'Pig Nose'),
    UnicodeEmoji('🐸', 'Frog Face'),
    UnicodeEmoji('🐵', 'Monkey Face'),
    UnicodeEmoji('🙈', 'See-No-Evil Monkey'),
    UnicodeEmoji('🙉', 'Hear-No-Evil Monkey'),
    UnicodeEmoji('🙊', 'Speak-No-Evil Monkey'),
    UnicodeEmoji('🐒', 'Monkey'),
    UnicodeEmoji('💥', 'Collision'),
    UnicodeEmoji('💫', 'Dizzy'),
    UnicodeEmoji('💦', 'Sweat Droplets'),
    UnicodeEmoji('💨', 'Dashing Away'),
    UnicodeEmoji('🦍', 'Gorilla'),
    UnicodeEmoji('🐕', 'Dog'),
    UnicodeEmoji('🐩', 'Poodle'),
    UnicodeEmoji('🐺', 'Wolf Face'),
    UnicodeEmoji('🦝', 'Raccoon'),
    UnicodeEmoji('🐈', 'Cat'),
    UnicodeEmoji('🐅', 'Tiger'),
    UnicodeEmoji('🐆', 'Leopard'),
    UnicodeEmoji('🐴', 'Horse Face'),
    UnicodeEmoji('🐎', 'Horse'),
    UnicodeEmoji('🦄', 'Unicorn Face'),
    UnicodeEmoji('🦓', 'Zebra'),
    UnicodeEmoji('🐂', 'Ox'),
    UnicodeEmoji('🐃', 'Water Buffalo'),
    UnicodeEmoji('🐄', 'Cow'),
    UnicodeEmoji('🐖', 'Pig'),
    UnicodeEmoji('🐗', 'Boar'),
    UnicodeEmoji('🐏', 'Ram'),
    UnicodeEmoji('🐑', 'Ewe'),
    UnicodeEmoji('🐐', 'Goat'),
    UnicodeEmoji('🐪', 'Camel'),
    UnicodeEmoji('🐫', 'Two-Hump Camel'),
    UnicodeEmoji('🦙', 'Llama'),
    UnicodeEmoji('🦒', 'Giraffe'),
    UnicodeEmoji('🐘', 'Elephant'),
    UnicodeEmoji('🦏', 'Rhinoceros'),
    UnicodeEmoji('🦛', 'Hippopotamus'),
    UnicodeEmoji('🐁', 'Mouse'),
    UnicodeEmoji('🐀', 'Rat'),
    UnicodeEmoji('🐇', 'Rabbit'),
    UnicodeEmoji('🐿️', 'Chipmunk'),
    UnicodeEmoji('🦔', 'Hedgehog'),
    UnicodeEmoji('🦇', 'Bat'),
    UnicodeEmoji('🦘', 'Kangaroo'),
    UnicodeEmoji('🦡', 'Badger'),
    UnicodeEmoji('🐾', 'Paw Prints'),
    UnicodeEmoji('🦃', 'Turkey'),
    UnicodeEmoji('🐔', 'Chicken'),
    UnicodeEmoji('🐓', 'Rooster'),
    UnicodeEmoji('🐣', 'Hatching Chick'),
    UnicodeEmoji('🐤', 'Baby Chick'),
    UnicodeEmoji('🐥', 'Front-Facing Baby Chick'),
    UnicodeEmoji('🐦', 'Bird'),
    UnicodeEmoji('🐧', 'Penguin'),
    UnicodeEmoji('🕊️', 'Dove'),
    UnicodeEmoji('🦅', 'Eagle'),
    UnicodeEmoji('🦆', 'Duck'),
    UnicodeEmoji('🦢', 'Swan'),
    UnicodeEmoji('🦉', 'Owl'),
    UnicodeEmoji('🦚', 'Peacock'),
    UnicodeEmoji('🦜', 'Parrot'),
    UnicodeEmoji('🐊', 'Crocodile'),
    UnicodeEmoji('🐢', 'Turtle'),
    UnicodeEmoji('🦎', 'Lizard'),
    UnicodeEmoji('🐍', 'Snake'),
    UnicodeEmoji('🐲', 'Dragon Face'),
    UnicodeEmoji('🐉', 'Dragon'),
    UnicodeEmoji('🦕', 'Sauropod'),
    UnicodeEmoji('🦖', 'T-Rex'),
    UnicodeEmoji('🧌', 'Troll'),
    UnicodeEmoji('🐳', 'Spouting Whale'),
    UnicodeEmoji('🐋', 'Whale'),
    UnicodeEmoji('🐬', 'Dolphin'),
    UnicodeEmoji('🐟', 'Fish'),
    UnicodeEmoji('🐠', 'Tropical Fish'),
    UnicodeEmoji('🐡', 'Blowfish'),
    UnicodeEmoji('🦈', 'Shark'),
    UnicodeEmoji('🐙', 'Octopus'),
    UnicodeEmoji('🪹', 'Empty Nest'),
    UnicodeEmoji('🪺', 'Nest with Eggs'),
    UnicodeEmoji('🐚', 'Spiral Shell'),
    UnicodeEmoji('🪸', 'Coral'),
    UnicodeEmoji('🐌', 'Snail'),
    UnicodeEmoji('🦋', 'Butterfly'),
    UnicodeEmoji('🐛', 'Bug'),
    UnicodeEmoji('🐜', 'Ant'),
    UnicodeEmoji('🐝', 'Honeybee'),
    UnicodeEmoji('🐞', 'Lady Beetle'),
    UnicodeEmoji('🦗', 'Cricket'),
    UnicodeEmoji('🕷️', 'Spider'),
    UnicodeEmoji('🕸️', 'Spider Web'),
    UnicodeEmoji('🦂', 'Scorpion'),
    UnicodeEmoji('🦟', 'Mosquito'),
    UnicodeEmoji('🦠', 'Microbe'),
    UnicodeEmoji('💐', 'Bouquet'),
    UnicodeEmoji('🌸', 'Cherry Blossom'),
    UnicodeEmoji('💮', 'White Flower'),
    UnicodeEmoji('🏵️', 'Rosette'),
    UnicodeEmoji('🪷', 'Lotus'),
    UnicodeEmoji('🌹', 'Rose'),
    UnicodeEmoji('🥀', 'Wilted Flower'),
    UnicodeEmoji('🌺', 'Hibiscus'),
    UnicodeEmoji('🌻', 'Sunflower'),
    UnicodeEmoji('🌼', 'Blossom'),
    UnicodeEmoji('🌷', 'Tulip'),
    UnicodeEmoji('🌱', 'Seedling'),
    UnicodeEmoji('🌲', 'Evergreen Tree'),
    UnicodeEmoji('🌳', 'Deciduous Tree'),
    UnicodeEmoji('🌴', 'Palm Tree'),
    UnicodeEmoji('🌵', 'Cactus'),
    UnicodeEmoji('🌾', 'Sheaf of Rice'),
    UnicodeEmoji('🌿', 'Herb'),
    UnicodeEmoji('☘️', 'Shamrock'),
    UnicodeEmoji('🍀', 'Four Leaf Clover'),
    UnicodeEmoji('🍁', 'Maple Leaf'),
    UnicodeEmoji('🍂', 'Fallen Leaf'),
    UnicodeEmoji('🍃', 'Leaf Fluttering in Wind'),
    UnicodeEmoji('🍄', 'Mushroom'),
    UnicodeEmoji('🌰', 'Chestnut'),
    UnicodeEmoji('🦀', 'Crab'),
    UnicodeEmoji('🦞', 'Lobster'),
    UnicodeEmoji('🦐', 'Shrimp'),
    UnicodeEmoji('🦑', 'Squid'),
    UnicodeEmoji('🌍', 'Globe Showing Europe-Africa'),
    UnicodeEmoji('🌎', 'Globe Showing Americas'),
    UnicodeEmoji('🌏', 'Globe Showing Asia-Australia'),
    UnicodeEmoji('🌐', 'Globe With Meridians'),
    UnicodeEmoji('🌑', 'New Moon'),
    UnicodeEmoji('🌒', 'Waxing Crescent Moon'),
    UnicodeEmoji('🌓', 'First Quarter Moon'),
    UnicodeEmoji('🌔', 'Waxing Gibbous Moon'),
    UnicodeEmoji('🌕', 'Full Moon'),
    UnicodeEmoji('🌖', 'Waning Gibbous Moon'),
    UnicodeEmoji('🌗', 'Last Quarter Moon'),
    UnicodeEmoji('🌘', 'Waning Crescent Moon'),
    UnicodeEmoji('🌙', 'Crescent Moon'),
    UnicodeEmoji('🌚', 'New Moon Face'),
    UnicodeEmoji('🌛', 'First Quarter Moon Face'),
    UnicodeEmoji('🌜', 'Last Quarter Moon Face'),
    UnicodeEmoji('☀️', 'Sun'),
    UnicodeEmoji('🌝', 'Full Moon Face'),
    UnicodeEmoji('🌞', 'Sun With Face'),
    UnicodeEmoji('⭐', 'Star'),
    UnicodeEmoji('🌟', 'Glowing Star'),
    UnicodeEmoji('🌠', 'Shooting Star'),
    UnicodeEmoji('☁️', 'Cloud'),
    UnicodeEmoji('⛅', 'Sun Behind Cloud'),
    UnicodeEmoji('⛈️', 'Cloud With Lightning and Rain'),
    UnicodeEmoji('🌤️', 'Sun Behind Small Cloud'),
    UnicodeEmoji('🌥️', 'Sun Behind Large Cloud'),
    UnicodeEmoji('🌦️', 'Sun Behind Rain Cloud'),
    UnicodeEmoji('🌧️', 'Cloud With Rain'),
    UnicodeEmoji('🌨️', 'Cloud With Snow'),
    UnicodeEmoji('🌩️', 'Cloud With Lightning'),
    UnicodeEmoji('🌪️', 'Tornado'),
    UnicodeEmoji('🌫️', 'Fog'),
    UnicodeEmoji('🌬️', 'Wind Face'),
    UnicodeEmoji('🌈', 'Rainbow'),
    UnicodeEmoji('☂️', 'Umbrella'),
    UnicodeEmoji('☔', 'Umbrella With Rain Drops'),
    UnicodeEmoji('⚡', 'High Voltage'),
    UnicodeEmoji('❄️', 'Snowflake'),
    UnicodeEmoji('☃️', 'Snowman'),
    UnicodeEmoji('⛄', 'Snowman Without Snow'),
    UnicodeEmoji('☄️', 'Comet'),
    UnicodeEmoji('🔥', 'Fire'),
    UnicodeEmoji('💧', 'Droplet'),
    UnicodeEmoji('🫧', 'Bubbles'),
    UnicodeEmoji('🌊', 'Water Wave'),
    UnicodeEmoji('🎄', 'Christmas Tree'),
    UnicodeEmoji('✨', 'Sparkles'),
    UnicodeEmoji('🎋', 'Tanabata Tree'),
    UnicodeEmoji('🎍', 'Pine Decoration')
  ]),

// ======================================================= Category.FOODS
  CategoryEmoji(Category.FOODS, [
    UnicodeEmoji('🍇', 'Grapes'),
    UnicodeEmoji('🍈', 'Melon'),
    UnicodeEmoji('🍉', 'Watermelon'),
    UnicodeEmoji('🍊', 'Tangerine'),
    UnicodeEmoji('🍋', 'Lemon'),
    UnicodeEmoji('🍌', 'Banana'),
    UnicodeEmoji('🍍', 'Pineapple'),
    UnicodeEmoji('🥭', 'Mango'),
    UnicodeEmoji('🍎', 'Red Apple'),
    UnicodeEmoji('🍏', 'Green Apple'),
    UnicodeEmoji('🍐', 'Pear'),
    UnicodeEmoji('🍑', 'Peach'),
    UnicodeEmoji('🍒', 'Cherries'),
    UnicodeEmoji('🍓', 'Strawberry'),
    UnicodeEmoji('🥝', 'Kiwi Fruit'),
    UnicodeEmoji('🍅', 'Tomato'),
    UnicodeEmoji('🥥', 'Coconut'),
    UnicodeEmoji('🥑', 'Avocado'),
    UnicodeEmoji('🍆', 'Eggplant'),
    UnicodeEmoji('🥔', 'Potato'),
    UnicodeEmoji('🥕', 'Carrot'),
    UnicodeEmoji('🌽', 'Ear of Corn'),
    UnicodeEmoji('🌶️', 'Hot Pepper'),
    UnicodeEmoji('🥒', 'Cucumber'),
    UnicodeEmoji('🥬', 'Leafy Green'),
    UnicodeEmoji('🥦', 'Broccoli'),
    UnicodeEmoji('🍄', 'Mushroom'),
    UnicodeEmoji('🥜', 'Peanuts'),
    UnicodeEmoji('🫘', 'Beans'),
    UnicodeEmoji('🌰', 'Chestnut'),
    UnicodeEmoji('🍞', 'Bread'),
    UnicodeEmoji('🥐', 'Croissant'),
    UnicodeEmoji('🥖', 'Baguette Bread'),
    UnicodeEmoji('🥨', 'Pretzel'),
    UnicodeEmoji('🥯', 'Bagel'),
    UnicodeEmoji('🥞', 'Pancakes'),
    UnicodeEmoji('🧀', 'Cheese Wedge'),
    UnicodeEmoji('🍖', 'Meat on Bone'),
    UnicodeEmoji('🍗', 'Poultry Leg'),
    UnicodeEmoji('🥩', 'Cut of Meat'),
    UnicodeEmoji('🥓', 'Bacon'),
    UnicodeEmoji('🍔', 'Hamburger'),
    UnicodeEmoji('🍟', 'French Fries'),
    UnicodeEmoji('🍕', 'Pizza'),
    UnicodeEmoji('🌭', 'Hot Dog'),
    UnicodeEmoji('🥪', 'Sandwich'),
    UnicodeEmoji('🌮', 'Taco'),
    UnicodeEmoji('🌯', 'Burrito'),
    UnicodeEmoji('🥙', 'Stuffed Flatbread'),
    UnicodeEmoji('🍳', 'Cooking'),
    UnicodeEmoji('🥘', 'Shallow Pan of Food'),
    UnicodeEmoji('🍲', 'Pot of Food'),
    UnicodeEmoji('🥣', 'Bowl With Spoon'),
    UnicodeEmoji('🥗', 'Green Salad'),
    UnicodeEmoji('🍿', 'Popcorn'),
    UnicodeEmoji('🧂', 'Salt'),
    UnicodeEmoji('🥫', 'Canned Food'),
    UnicodeEmoji('🫙', 'Jar'),
    UnicodeEmoji('🍱', 'Bento Box'),
    UnicodeEmoji('🍘', 'Rice Cracker'),
    UnicodeEmoji('🍙', 'Rice Ball'),
    UnicodeEmoji('🍚', 'Cooked Rice'),
    UnicodeEmoji('🍛', 'Curry Rice'),
    UnicodeEmoji('🍜', 'Steaming Bowl'),
    UnicodeEmoji('🍝', 'Spaghetti'),
    UnicodeEmoji('🍠', 'Roasted Sweet Potato'),
    UnicodeEmoji('🍢', 'Oden'),
    UnicodeEmoji('🍣', 'Sushi'),
    UnicodeEmoji('🍤', 'Fried Shrimp'),
    UnicodeEmoji('🍥', 'Fish Cake With Swirl'),
    UnicodeEmoji('🥮', 'Moon Cake'),
    UnicodeEmoji('🍡', 'Dango'),
    UnicodeEmoji('🥟', 'Dumpling'),
    UnicodeEmoji('🥠', 'Fortune Cookie'),
    UnicodeEmoji('🥡', 'Takeout Box'),
    UnicodeEmoji('🍦', 'Soft Ice Cream'),
    UnicodeEmoji('🍧', 'Shaved Ice'),
    UnicodeEmoji('🍨', 'Ice Cream'),
    UnicodeEmoji('🍩', 'Doughnut'),
    UnicodeEmoji('🍪', 'Cookie'),
    UnicodeEmoji('🎂', 'Birthday Cake'),
    UnicodeEmoji('🍰', 'Shortcake'),
    UnicodeEmoji('🧁', 'Cupcake'),
    UnicodeEmoji('🥧', 'Pie'),
    UnicodeEmoji('🍫', 'Chocolate Bar'),
    UnicodeEmoji('🍬', 'Candy'),
    UnicodeEmoji('🍭', 'Lollipop'),
    UnicodeEmoji('🍮', 'Custard'),
    UnicodeEmoji('🍯', 'Honey Pot'),
    UnicodeEmoji('🍼', 'Baby Bottle'),
    UnicodeEmoji('🥛', 'Glass of Milk'),
    UnicodeEmoji('🫗', 'Pouring Liquid'),
    UnicodeEmoji('☕', 'Hot Beverage'),
    UnicodeEmoji('🍵', 'Teacup Without Handle'),
    UnicodeEmoji('🧉', 'Mate Drink'),
    UnicodeEmoji('🍶', 'Sake'),
    UnicodeEmoji('🍾', 'Bottle With Popping Cork'),
    UnicodeEmoji('🍷', 'Wine Glass'),
    UnicodeEmoji('🍸', 'Cocktail Glass'),
    UnicodeEmoji('🍹', 'Tropical Drink'),
    UnicodeEmoji('🍺', 'Beer Mug'),
    UnicodeEmoji('🍻', 'Clinking Beer Mugs'),
    UnicodeEmoji('🥂', 'Clinking Glasses'),
    UnicodeEmoji('🥃', 'Tumbler Glass'),
    UnicodeEmoji('🥤', 'Cup With Straw'),
    UnicodeEmoji('🥢', 'Chopsticks'),
    UnicodeEmoji('🍽️', 'Fork and Knife With Plate'),
    UnicodeEmoji('🍴', 'Fork and Knife'),
    UnicodeEmoji('🥄', 'Spoon')
  ]),

// ======================================================= Category.TRAVEL
  CategoryEmoji(Category.TRAVEL, [
    UnicodeEmoji('🗾', 'Map of Japan'),
    UnicodeEmoji('🏔️', 'Snow-Capped Mountain'),
    UnicodeEmoji('⛰️', 'Mountain'),
    UnicodeEmoji('🌋', 'Volcano'),
    UnicodeEmoji('🗻', 'Mount Fuji'),
    UnicodeEmoji('🏕️', 'Camping'),
    UnicodeEmoji('🏖️', 'Beach With Umbrella'),
    UnicodeEmoji('🏜️', 'Desert'),
    UnicodeEmoji('🏝️', 'Desert Island'),
    UnicodeEmoji('🏞️', 'National Park'),
    UnicodeEmoji('🏟️', 'Stadium'),
    UnicodeEmoji('🏛️', 'Classical Building'),
    UnicodeEmoji('🏗️', 'Building Construction'),
    UnicodeEmoji('🏘️', 'Houses'),
    UnicodeEmoji('🏚️', 'Derelict House'),
    UnicodeEmoji('🏠', 'House'),
    UnicodeEmoji('🏡', 'House With Garden'),
    UnicodeEmoji('🏢', 'Office Building'),
    UnicodeEmoji('🏣', 'Japanese Post Office'),
    UnicodeEmoji('🏤', 'Post Office'),
    UnicodeEmoji('🏥', 'Hospital'),
    UnicodeEmoji('🏦', 'Bank'),
    UnicodeEmoji('🏨', 'Hotel'),
    UnicodeEmoji('🏩', 'Love Hotel'),
    UnicodeEmoji('🏪', 'Convenience Store'),
    UnicodeEmoji('🏫', 'School'),
    UnicodeEmoji('🏬', 'Department Store'),
    UnicodeEmoji('🏭', 'Factory'),
    UnicodeEmoji('🏯', 'Japanese Castle'),
    UnicodeEmoji('🏰', 'Castle'),
    UnicodeEmoji('💒', 'Wedding'),
    UnicodeEmoji('🗼', 'Tokyo Tower'),
    UnicodeEmoji('🗽', 'Statue of Liberty'),
    UnicodeEmoji('⛪', 'Church'),
    UnicodeEmoji('🕌', 'Mosque'),
    UnicodeEmoji('🕍', 'Synagogue'),
    UnicodeEmoji('⛩️', 'Shinto Shrine'),
    UnicodeEmoji('🕋', 'Kaaba'),
    UnicodeEmoji('⛲', 'Fountain'),
    UnicodeEmoji('⛺', 'Tent'),
    UnicodeEmoji('🌁', 'Foggy'),
    UnicodeEmoji('🌃', 'Night With Stars'),
    UnicodeEmoji('🏙️', 'Cityscape'),
    UnicodeEmoji('🌄', 'Sunrise Over Mountains'),
    UnicodeEmoji('🌅', 'Sunrise'),
    UnicodeEmoji('🌆', 'Cityscape at Dusk'),
    UnicodeEmoji('🌇', 'Sunset'),
    UnicodeEmoji('🌉', 'Bridge at Night'),
    UnicodeEmoji('🎠', 'Carousel Horse'),
    UnicodeEmoji('🎡', 'Ferris Wheel'),
    UnicodeEmoji('🎢', 'Roller Coaster'),
    UnicodeEmoji('🚂', 'Locomotive'),
    UnicodeEmoji('🚃', 'Railway Car'),
    UnicodeEmoji('🚄', 'High-Speed Train'),
    UnicodeEmoji('🚅', 'Bullet Train'),
    UnicodeEmoji('🚆', 'Train'),
    UnicodeEmoji('🚇', 'Metro'),
    UnicodeEmoji('🚈', 'Light Rail'),
    UnicodeEmoji('🚉', 'Station'),
    UnicodeEmoji('🚊', 'Tram'),
    UnicodeEmoji('🚝', 'Monorail'),
    UnicodeEmoji('🚞', 'Mountain Railway'),
    UnicodeEmoji('🚋', 'Tram Car'),
    UnicodeEmoji('🚌', 'Bus'),
    UnicodeEmoji('🚍', 'Oncoming Bus'),
    UnicodeEmoji('🚎', 'Trolleybus'),
    UnicodeEmoji('🚐', 'Minibus'),
    UnicodeEmoji('🚑', 'Ambulance'),
    UnicodeEmoji('🚒', 'Fire Engine'),
    UnicodeEmoji('🚓', 'Police Car'),
    UnicodeEmoji('🚔', 'Oncoming Police Car'),
    UnicodeEmoji('🚕', 'Taxi'),
    UnicodeEmoji('🚖', 'Oncoming Taxi'),
    UnicodeEmoji('🚗', 'Automobile'),
    UnicodeEmoji('🚘', 'Oncoming Automobile'),
    UnicodeEmoji('🚚', 'Delivery Truck'),
    UnicodeEmoji('🚛', 'Articulated Lorry'),
    UnicodeEmoji('🚜', 'Tractor'),
    UnicodeEmoji('🏎️', 'Racing Car'),
    UnicodeEmoji('🏍️', 'Motorcycle'),
    UnicodeEmoji('🛵', 'Motor Scooter'),
    UnicodeEmoji('🚲', 'Bicycle'),
    UnicodeEmoji('🛴', 'Kick Scooter'),
    UnicodeEmoji('🚏', 'Bus Stop'),
    UnicodeEmoji('🛤️', 'Railway Track'),
    UnicodeEmoji('⛽', 'Fuel Pump'),
    UnicodeEmoji('🛞', 'Wheel'),
    UnicodeEmoji('🚨', 'Police Car Light'),
    UnicodeEmoji('🚥', 'Horizontal Traffic Light'),
    UnicodeEmoji('🚦', 'Vertical Traffic Light'),
    UnicodeEmoji('🚧', 'Construction'),
    UnicodeEmoji('⚓', 'Anchor'),
    UnicodeEmoji('⛵', 'Sailboat'),
    UnicodeEmoji('🚤', 'Speedboat'),
    UnicodeEmoji('🛳️', 'Passenger Ship'),
    UnicodeEmoji('⛴️', 'Ferry'),
    UnicodeEmoji('🛥️', 'Motor Boat'),
    UnicodeEmoji('🚢', 'Ship'),
    UnicodeEmoji('🛟', 'Ring Buoy'),
    UnicodeEmoji('✈️', 'Airplane'),
    UnicodeEmoji('🛩️', 'Small Airplane'),
    UnicodeEmoji('🛫', 'Airplane Departure'),
    UnicodeEmoji('🛬', 'Airplane Arrival'),
    UnicodeEmoji('💺', 'Seat'),
    UnicodeEmoji('🚁', 'Helicopter'),
    UnicodeEmoji('🚟', 'Suspension Railway'),
    UnicodeEmoji('🚠', 'Mountain Cableway'),
    UnicodeEmoji('🚡', 'Aerial Tramway'),
    UnicodeEmoji('🛰️', 'Satellite'),
    UnicodeEmoji('🚀', 'Rocket'),
    UnicodeEmoji('🛸', 'Flying Saucer'),
    UnicodeEmoji('🌠', 'Shooting Star'),
    UnicodeEmoji('🌌', 'Milky Way'),
    UnicodeEmoji('⛱️', 'Umbrella on Ground'),
    UnicodeEmoji('🎆', 'Fireworks'),
    UnicodeEmoji('🎇', 'Sparkler'),
    UnicodeEmoji('🎑', 'Moon Viewing Ceremony'),
    UnicodeEmoji('🗿', 'Moai'),
    UnicodeEmoji('🛂', 'Passport Control'),
    UnicodeEmoji('🛃', 'Customs'),
    UnicodeEmoji('🛄', 'Baggage Claim'),
    UnicodeEmoji('🛅', 'Left Luggage')
  ]),

// ======================================================= Category.ACTIVITIES
  CategoryEmoji(Category.ACTIVITIES, [
    UnicodeEmoji('🧗‍♂️', 'Man Climbing', hasSkinTone: true),
    UnicodeEmoji('🧗‍♀️', 'Woman Climbing', hasSkinTone: true),
    UnicodeEmoji('🏇', 'Horse Racing', hasSkinTone: true),
    UnicodeEmoji('⛷️', 'Skier'),
    UnicodeEmoji('🏂', 'Snowboarder'),
    UnicodeEmoji('🏌️‍♂️', 'Man Golfing', hasSkinTone: true),
    UnicodeEmoji('🏌️‍♀️', 'Woman Golfing', hasSkinTone: true),
    UnicodeEmoji('🏄‍♂️', 'Man Surfing', hasSkinTone: true),
    UnicodeEmoji('🏄‍♀️', 'Woman Surfing', hasSkinTone: true),
    UnicodeEmoji('🚣‍♂️', 'Man Rowing Boat', hasSkinTone: true),
    UnicodeEmoji('🚣‍♀️', 'Woman Rowing Boat', hasSkinTone: true),
    UnicodeEmoji('🏊‍♂️', 'Man Swimming', hasSkinTone: true),
    UnicodeEmoji('🏊‍♀️', 'Woman Swimming', hasSkinTone: true),
    UnicodeEmoji('⛹️‍♂️', 'Man Bouncing Ball', hasSkinTone: true),
    UnicodeEmoji('⛹️‍♀️', 'Woman Bouncing Ball', hasSkinTone: true),
    UnicodeEmoji('🏋️‍♂️', 'Man Lifting Weights', hasSkinTone: true),
    UnicodeEmoji('🏋️‍♀️', 'Woman Lifting Weights', hasSkinTone: true),
    UnicodeEmoji('🚴‍♂️', 'Man Biking', hasSkinTone: true),
    UnicodeEmoji('🚴‍♀️', 'Woman Biking', hasSkinTone: true),
    UnicodeEmoji('🚵‍♂️', 'Man Mountain Biking', hasSkinTone: true),
    UnicodeEmoji('🚵‍♀️', 'Woman Mountain Biking', hasSkinTone: true),
    UnicodeEmoji('🤸‍♂️', 'Man Cartwheeling', hasSkinTone: true),
    UnicodeEmoji('🤸‍♀️', 'Woman Cartwheeling', hasSkinTone: true),
    UnicodeEmoji('🤼‍♂️', 'Men Wrestling', hasSkinTone: true),
    UnicodeEmoji('🤼‍♀️', 'Women Wrestling', hasSkinTone: true),
    UnicodeEmoji('🤽‍♂️', 'Man Playing Water Polo', hasSkinTone: true),
    UnicodeEmoji('🤽‍♀️', 'Woman Playing Water Polo', hasSkinTone: true),
    UnicodeEmoji('🤾‍♂️', 'Man Playing Handball', hasSkinTone: true),
    UnicodeEmoji('🤾‍♀️', 'Woman Playing Handball', hasSkinTone: true),
    UnicodeEmoji('🤹‍♂️', 'Man Juggling', hasSkinTone: true),
    UnicodeEmoji('🤹‍♀️', 'Woman Juggling', hasSkinTone: true),
    UnicodeEmoji('🧘‍♂️', 'Man in Lotus Position', hasSkinTone: true),
    UnicodeEmoji('🧘‍♀️', 'Woman in Lotus Position', hasSkinTone: true),
    UnicodeEmoji('🎪', 'Circus Tent'),
    UnicodeEmoji('🛹', 'Skateboard'),
    UnicodeEmoji('🎗️', 'Reminder Ribbon'),
    UnicodeEmoji('🎟️', 'Admission Tickets'),
    UnicodeEmoji('🎫', 'Ticket'),
    UnicodeEmoji('🎖️', 'Military Medal'),
    UnicodeEmoji('🏆', 'Trophy'),
    UnicodeEmoji('🏅', 'Sports Medal'),
    UnicodeEmoji('🥇', '1st Place Medal'),
    UnicodeEmoji('🥈', '2nd Place Medal'),
    UnicodeEmoji('🥉', '3rd Place Medal'),
    UnicodeEmoji('⚽', 'Soccer Ball'),
    UnicodeEmoji('⚾', 'Baseball'),
    UnicodeEmoji('🥎', 'Softball'),
    UnicodeEmoji('🏀', 'Basketball'),
    UnicodeEmoji('🏐', 'Volleyball'),
    UnicodeEmoji('🏈', 'American Football'),
    UnicodeEmoji('🏉', 'Rugby Football'),
    UnicodeEmoji('🎾', 'Tennis'),
    UnicodeEmoji('🥏', 'Flying Disc'),
    UnicodeEmoji('🎳', 'Bowling'),
    UnicodeEmoji('🏏', 'Cricket Game'),
    UnicodeEmoji('🏑', 'Field Hockey'),
    UnicodeEmoji('🏒', 'Ice Hockey'),
    UnicodeEmoji('🥍', 'Lacrosse'),
    UnicodeEmoji('🏓', 'Ping Pong'),
    UnicodeEmoji('🏸', 'Badminton'),
    UnicodeEmoji('🪃', 'Boomerang'),
    UnicodeEmoji('🥅', 'Goal Net'),
    UnicodeEmoji('⛳', 'Flag in Hole'),
    UnicodeEmoji('🪁', 'Kite'),
    UnicodeEmoji('🛝', 'Playground Slide'),
    UnicodeEmoji('🏹', 'Bow and Arrow'),
    UnicodeEmoji('🎣', 'Fishing Pole'),
    UnicodeEmoji('🤿 ', 'Diving Mask'),
    UnicodeEmoji('🥊', 'Boxing Glove'),
    UnicodeEmoji('🥋', 'Martial Arts Uniform'),
    UnicodeEmoji('🎽', 'Running Shirt'),
    UnicodeEmoji('🛼', 'Roller Skate'),
    UnicodeEmoji('🛷', 'Sled'),
    UnicodeEmoji('⛸️', 'Ice Skate'),
    UnicodeEmoji('🥌', 'Curling Stone'),
    UnicodeEmoji('🎿', 'Skis'),
    UnicodeEmoji('🎯', 'Direct Hit'),
    UnicodeEmoji('🎱', 'Pool 8 Ball'),
    UnicodeEmoji('🎮', 'Video Game'),
    UnicodeEmoji('🎰', 'Slot Machine'),
    UnicodeEmoji('🎲', 'Game Die'),
    UnicodeEmoji('🧩', 'Jigsaw'),
    UnicodeEmoji('♟️', 'Chess Pawn'),
    UnicodeEmoji('🎭', 'Performing Arts'),
    UnicodeEmoji('🎨', 'Artist Palette'),
    UnicodeEmoji('🧵', 'Thread'),
    UnicodeEmoji('🧶', 'Yarn'),
    UnicodeEmoji('🎼', 'Musical Score'),
    UnicodeEmoji('🎤', 'Microphone'),
    UnicodeEmoji('🎧', 'Headphone'),
    UnicodeEmoji('🎷', 'Saxophone'),
    UnicodeEmoji('🎸', 'Guitar'),
    UnicodeEmoji('🎹', 'Musical Keyboard'),
    UnicodeEmoji('🎺', 'Trumpet'),
    UnicodeEmoji('🎻', 'Violin'),
    UnicodeEmoji('🥁', 'Drum'),
    UnicodeEmoji('🎬', 'Clapper Board')
  ]),

// ======================================================= Category.OBJECTS
  CategoryEmoji(Category.OBJECTS, [
    UnicodeEmoji('💌', 'Love Letter'),
    UnicodeEmoji('🕳️', 'Hole'),
    UnicodeEmoji('💣', 'Bomb'),
    UnicodeEmoji('🛀', 'Person Taking Bath'),
    UnicodeEmoji('🛌', 'Person in Bed'),
    UnicodeEmoji('🏺', 'Amphora'),
    UnicodeEmoji('🗺️', 'World Map'),
    UnicodeEmoji('🧭', 'Compass'),
    UnicodeEmoji('🧱', 'Brick'),
    UnicodeEmoji('💈', 'Barber Pole'),
    UnicodeEmoji('🛢️', 'Oil Drum'),
    UnicodeEmoji('🛎️', 'Bellhop Bell'),
    UnicodeEmoji('🧳', 'Luggage'),
    UnicodeEmoji('⌛', 'Hourglass Done'),
    UnicodeEmoji('⏳', 'Hourglass Not Done'),
    UnicodeEmoji('⌚', 'Watch'),
    UnicodeEmoji('⏰', 'Alarm Clock'),
    UnicodeEmoji('⏱️', 'Stopwatch'),
    UnicodeEmoji('⏲️', 'Timer Clock'),
    UnicodeEmoji('🕰️', 'Mantelpiece Clock'),
    UnicodeEmoji('🌡️', 'Thermometer'),
    UnicodeEmoji('⛱️', 'Umbrella on Ground'),
    UnicodeEmoji('🧨', 'Firecracker'),
    UnicodeEmoji('🎈', 'Balloon'),
    UnicodeEmoji('🎉', 'Party Popper'),
    UnicodeEmoji('🎊', 'Confetti Ball'),
    UnicodeEmoji('🎎', 'Japanese Dolls'),
    UnicodeEmoji('🎏', 'Carp Streamer'),
    UnicodeEmoji('🎐', 'Wind Chime'),
    UnicodeEmoji('🪩', 'Mirror Ball'),
    UnicodeEmoji('🧧', 'Red Envelope'),
    UnicodeEmoji('🎀', 'Ribbon'),
    UnicodeEmoji('🎁', 'Wrapped Gift'),
    UnicodeEmoji('🔮', 'Crystal Ball'),
    UnicodeEmoji('🧿', 'Nazar Amulet'),
    UnicodeEmoji('🪬', 'Hamsa'),
    UnicodeEmoji('🕹️', 'Joystick'),
    UnicodeEmoji('🧸', 'Teddy Bear'),
    UnicodeEmoji('🖼️', 'Framed Picture'),
    UnicodeEmoji('🧵', 'Thread'),
    UnicodeEmoji('🧶', 'Yarn'),
    UnicodeEmoji('🛍️', 'Shopping Bags'),
    UnicodeEmoji('📿', 'Prayer Beads'),
    UnicodeEmoji('💎', 'Gem Stone'),
    UnicodeEmoji('📯', 'Postal Horn'),
    UnicodeEmoji('🎙️', 'Studio Microphone'),
    UnicodeEmoji('🎚️', 'Level Slider'),
    UnicodeEmoji('🎛️', 'Control Knobs'),
    UnicodeEmoji('📻', 'Radio'),
    UnicodeEmoji('📱', 'Mobile Phone'),
    UnicodeEmoji('📲', 'Mobile Phone With Arrow'),
    UnicodeEmoji('☎️', 'Telephone'),
    UnicodeEmoji('📞', 'Telephone Receiver'),
    UnicodeEmoji('📟', 'Pager'),
    UnicodeEmoji('📠', 'Fax Machine'),
    UnicodeEmoji('🔋', 'Battery'),
    UnicodeEmoji('🪫', 'Low Battery'),
    UnicodeEmoji('🔌', 'Electric Plug'),
    UnicodeEmoji('💻', 'Laptop Computer'),
    UnicodeEmoji('🖥️', 'Desktop Computer'),
    UnicodeEmoji('🖨️', 'Printer'),
    UnicodeEmoji('⌨️', 'Keyboard'),
    UnicodeEmoji('🖱️', 'Computer Mouse'),
    UnicodeEmoji('🖲️', 'Trackball'),
    UnicodeEmoji('💽', 'Computer Disk'),
    UnicodeEmoji('💾', 'Floppy Disk'),
    UnicodeEmoji('💿', 'Optical Disk'),
    UnicodeEmoji('📀', 'DVD'),
    UnicodeEmoji('🧮', 'Abacus'),
    UnicodeEmoji('🎥', 'Movie Camera'),
    UnicodeEmoji('🎞️', 'Film Frames'),
    UnicodeEmoji('📽️', 'Film Projector'),
    UnicodeEmoji('📺', 'Television'),
    UnicodeEmoji('📷', 'Camera'),
    UnicodeEmoji('📸', 'Camera With Flash'),
    UnicodeEmoji('📹', 'Video Camera'),
    UnicodeEmoji('📼', 'Videocassette'),
    UnicodeEmoji('🔍', 'Magnifying Glass Tilted Left'),
    UnicodeEmoji('🔎', 'Magnifying Glass Tilted Right'),
    UnicodeEmoji('🕯️', 'Candle'),
    UnicodeEmoji('💡', 'Light Bulb'),
    UnicodeEmoji('🔦', 'Flashlight'),
    UnicodeEmoji('🏮', 'Red Paper Lantern'),
    UnicodeEmoji('📔', 'Notebook With Decorative Cover'),
    UnicodeEmoji('📕', 'Closed Book'),
    UnicodeEmoji('📖', 'Open Book'),
    UnicodeEmoji('📗', 'Green Book'),
    UnicodeEmoji('📘', 'Blue Book'),
    UnicodeEmoji('📙', 'Orange Book'),
    UnicodeEmoji('📚', 'Books'),
    UnicodeEmoji('📓', 'Notebook'),
    UnicodeEmoji('📃', 'Page With Curl'),
    UnicodeEmoji('📜', 'Scroll'),
    UnicodeEmoji('📄', 'Page Facing Up'),
    UnicodeEmoji('📰', 'Newspaper'),
    UnicodeEmoji('🗞️', 'Rolled-Up Newspaper'),
    UnicodeEmoji('📑', 'Bookmark Tabs'),
    UnicodeEmoji('🔖', 'Bookmark'),
    UnicodeEmoji('🏷️', 'Label'),
    UnicodeEmoji('💰', 'Money Bag'),
    UnicodeEmoji('💴', 'Yen Banknote'),
    UnicodeEmoji('💵', 'Dollar Banknote'),
    UnicodeEmoji('💶', 'Euro Banknote'),
    UnicodeEmoji('💷', 'Pound Banknote'),
    UnicodeEmoji('💸', 'Money With Wings'),
    UnicodeEmoji('💳', 'Credit Card'),
    UnicodeEmoji('🪪', 'Identification Card'),
    UnicodeEmoji('🧾', 'Receipt'),
    UnicodeEmoji('✉️', 'Envelope'),
    UnicodeEmoji('📧', 'E-Mail'),
    UnicodeEmoji('📨', 'Incoming Envelope'),
    UnicodeEmoji('📩', 'Envelope With Arrow'),
    UnicodeEmoji('📤', 'Outbox Tray'),
    UnicodeEmoji('📥', 'Inbox Tray'),
    UnicodeEmoji('📦', 'Package'),
    UnicodeEmoji('📫', 'Closed Mailbox With Raised Flag'),
    UnicodeEmoji('📪', 'Closed Mailbox With Lowered Flag'),
    UnicodeEmoji('📬', 'Open Mailbox With Raised Flag'),
    UnicodeEmoji('📭', 'Open Mailbox With Lowered Flag'),
    UnicodeEmoji('📮', 'Postbox'),
    UnicodeEmoji('🗳️', 'Ballot Box With Ballot'),
    UnicodeEmoji('✏️', 'Pencil'),
    UnicodeEmoji('✒️', 'Black Nib'),
    UnicodeEmoji('🖋️', 'Fountain Pen'),
    UnicodeEmoji('🖊️', 'Pen'),
    UnicodeEmoji('🖌️', 'Paintbrush'),
    UnicodeEmoji('🖍️', 'Crayon'),
    UnicodeEmoji('📝', 'Memo'),
    UnicodeEmoji('📁', 'File Folder'),
    UnicodeEmoji('📂', 'Open File Folder'),
    UnicodeEmoji('🗂️', 'Card Index Dividers'),
    UnicodeEmoji('📅', 'Calendar'),
    UnicodeEmoji('📆', 'Tear-Off Calendar'),
    UnicodeEmoji('🗒️', 'Spiral Notepad'),
    UnicodeEmoji('🗓️', 'Spiral Calendar'),
    UnicodeEmoji('📇', 'Card Index'),
    UnicodeEmoji('📈', 'Chart Increasing'),
    UnicodeEmoji('📉', 'Chart Decreasing'),
    UnicodeEmoji('📊', 'Bar Chart'),
    UnicodeEmoji('📋', 'Clipboard'),
    UnicodeEmoji('📌', 'Pushpin'),
    UnicodeEmoji('📍', 'Round Pushpin'),
    UnicodeEmoji('📎', 'Paperclip'),
    UnicodeEmoji('🖇️', 'Linked Paperclips'),
    UnicodeEmoji('📏', 'Straight Ruler'),
    UnicodeEmoji('📐', 'Triangular Ruler'),
    UnicodeEmoji('✂️', 'Scissors'),
    UnicodeEmoji('🗃️', 'Card File Box'),
    UnicodeEmoji('🗄️', 'File Cabinet'),
    UnicodeEmoji('🗑️', 'Wastebasket'),
    UnicodeEmoji('🔒', 'Locked'),
    UnicodeEmoji('🔓', 'Unlocked'),
    UnicodeEmoji('🔏', 'Locked With Pen'),
    UnicodeEmoji('🔐', 'Locked With Key'),
    UnicodeEmoji('🔑', 'Key'),
    UnicodeEmoji('🗝️', 'Old Key'),
    UnicodeEmoji('🔨', 'Hammer'),
    UnicodeEmoji('⛏️', 'Pick'),
    UnicodeEmoji('⚒️', 'Hammer and Pick'),
    UnicodeEmoji('🛠️', 'Hammer and Wrench'),
    UnicodeEmoji('🔪', 'Kitchen Knife'),
    UnicodeEmoji('🗡️', 'Dagger'),
    UnicodeEmoji('⚔️', 'Crossed Swords'),
    UnicodeEmoji('🔫', 'Pistol'),
    UnicodeEmoji('🛡️', 'Shield'),
    UnicodeEmoji('🔧', 'Wrench'),
    UnicodeEmoji('🔩', 'Nut and Bolt'),
    UnicodeEmoji('⚙️', 'Gear'),
    UnicodeEmoji('🗜️', 'Clamp'),
    UnicodeEmoji('⚖️', 'Balance Scale'),
    UnicodeEmoji('🔗', 'Link'),
    UnicodeEmoji('⛓️', 'Chains'),
    UnicodeEmoji('🧰', 'Toolbox'),
    UnicodeEmoji('🧲', 'Magnet'),
    UnicodeEmoji('⚗️', 'Alembic'),
    UnicodeEmoji('🧪', 'Test Tube'),
    UnicodeEmoji('🧫', 'Petri Dish'),
    UnicodeEmoji('🧬', 'DNA'),
    UnicodeEmoji('🔬', 'Microscope'),
    UnicodeEmoji('🩻', 'X-Ray'),
    UnicodeEmoji('🔭', 'Telescope'),
    UnicodeEmoji('📡', 'Satellite Antenna'),
    UnicodeEmoji('💉', 'Syringe'),
    UnicodeEmoji('💊', 'Pill'),
    UnicodeEmoji('🚪', 'Door'),
    UnicodeEmoji('🛏️', 'Bed'),
    UnicodeEmoji('🛋️', 'Couch and Lamp'),
    UnicodeEmoji('🚽', 'Toilet'),
    UnicodeEmoji('🚿', 'Shower'),
    UnicodeEmoji('🛁', 'Bathtub'),
    UnicodeEmoji('🧴', 'Lotion Bottle'),
    UnicodeEmoji('🧷', 'Safety Pin'),
    UnicodeEmoji('🧹', 'Broom'),
    UnicodeEmoji('🧺', 'Basket'),
    UnicodeEmoji('🧻', 'Roll of Paper'),
    UnicodeEmoji('🧼', 'Soap'),
    UnicodeEmoji('🧽', 'Sponge'),
    UnicodeEmoji('🧯', 'Fire Extinguisher'),
    UnicodeEmoji('🚬', 'Cigarette'),
    UnicodeEmoji('⚰️', 'Coffin'),
    UnicodeEmoji('⚱️', 'Funeral Urn'),
    UnicodeEmoji('🚰', 'Potable Water')
  ]),

// ======================================================= Category.SYMBOLS
  CategoryEmoji(Category.SYMBOLS, [
    UnicodeEmoji('💘', 'Heart With Arrow'),
    UnicodeEmoji('💝', 'Heart With Ribbon'),
    UnicodeEmoji('💖', 'Sparkling Heart'),
    UnicodeEmoji('💗', 'Growing Heart'),
    UnicodeEmoji('💓', 'Beating Heart'),
    UnicodeEmoji('💞', 'Revolving Hearts'),
    UnicodeEmoji('💕', 'Two Hearts'),
    UnicodeEmoji('💟', 'Heart Decoration'),
    UnicodeEmoji('❣️', 'Heavy Heart Exclamation'),
    UnicodeEmoji('💔', 'Broken Heart'),
    UnicodeEmoji('❤️', 'Red Heart'),
    UnicodeEmoji('🧡', 'Orange Heart'),
    UnicodeEmoji('💛', 'Yellow Heart'),
    UnicodeEmoji('💚', 'Green Heart'),
    UnicodeEmoji('💙', 'Blue Heart'),
    UnicodeEmoji('💜', 'Purple Heart'),
    UnicodeEmoji('🖤', 'Black Heart'),
    UnicodeEmoji('💯', 'Hundred Points'),
    UnicodeEmoji('💢', 'Anger Symbol'),
    UnicodeEmoji('💬', 'Speech Balloon'),
    UnicodeEmoji('👁️‍🗨️', 'Eye in Speech Bubble'),
    UnicodeEmoji('🗯️', 'Right Anger Bubble'),
    UnicodeEmoji('💭', 'Thought Balloon'),
    UnicodeEmoji('💤', 'Zzz'),
    UnicodeEmoji('💮', 'White Flower'),
    UnicodeEmoji('♨️', 'Hot Springs'),
    UnicodeEmoji('💈', 'Barber Pole'),
    UnicodeEmoji('🛑', 'Stop Sign'),
    UnicodeEmoji('🕛', 'Twelve O’Clock'),
    UnicodeEmoji('🕧', 'Twelve-Thirty'),
    UnicodeEmoji('🕐', 'One O’Clock'),
    UnicodeEmoji('🕜', 'One-Thirty'),
    UnicodeEmoji('🕑', 'Two O’Clock'),
    UnicodeEmoji('🕝', 'Two-Thirty'),
    UnicodeEmoji('🕒', 'Three O’Clock'),
    UnicodeEmoji('🕞', 'Three-Thirty'),
    UnicodeEmoji('🕓', 'Four O’Clock'),
    UnicodeEmoji('🕟', 'Four-Thirty'),
    UnicodeEmoji('🕔', 'Five O’Clock'),
    UnicodeEmoji('🕠', 'Five-Thirty'),
    UnicodeEmoji('🕕', 'Six O’Clock'),
    UnicodeEmoji('🕡', 'Six-Thirty'),
    UnicodeEmoji('🕖', 'Seven O’Clock'),
    UnicodeEmoji('🕢', 'Seven-Thirty'),
    UnicodeEmoji('🕗', 'Eight O’Clock'),
    UnicodeEmoji('🕣', 'Eight-Thirty'),
    UnicodeEmoji('🕘', 'Nine O’Clock'),
    UnicodeEmoji('🕤', 'Nine-Thirty'),
    UnicodeEmoji('🕙', 'Ten O’Clock'),
    UnicodeEmoji('🕥', 'Ten-Thirty'),
    UnicodeEmoji('🕚', 'Eleven O’Clock'),
    UnicodeEmoji('🕦', 'Eleven-Thirty'),
    UnicodeEmoji('🌀', 'Cyclone'),
    UnicodeEmoji('♠️', 'Spade Suit'),
    UnicodeEmoji('♥️', 'Heart Suit'),
    UnicodeEmoji('♦️', 'Diamond Suit'),
    UnicodeEmoji('♣️', 'Club Suit'),
    UnicodeEmoji('🃏', 'Joker'),
    UnicodeEmoji('🀄', 'Mahjong Red Dragon'),
    UnicodeEmoji('🎴', 'Flower Playing Cards'),
    UnicodeEmoji('🔇', 'Muted Speaker'),
    UnicodeEmoji('🔈', 'Speaker Low Volume'),
    UnicodeEmoji('🔉', 'Speaker Medium Volume'),
    UnicodeEmoji('🔊', 'Speaker High Volume'),
    UnicodeEmoji('📢', 'Loudspeaker'),
    UnicodeEmoji('📣', 'Megaphone'),
    UnicodeEmoji('📯', 'Postal Horn'),
    UnicodeEmoji('🔔', 'Bell'),
    UnicodeEmoji('🔕', 'Bell With Slash'),
    UnicodeEmoji('🎵', 'Musical Note'),
    UnicodeEmoji('🎶', 'Musical Notes'),
    UnicodeEmoji('🏧', 'ATM Sign'),
    UnicodeEmoji('🚮', 'Litter in Bin Sign'),
    UnicodeEmoji('🚰', 'Potable Water'),
    UnicodeEmoji('♿', 'Wheelchair Symbol'),
    UnicodeEmoji('🩼', 'Crutch'),
    UnicodeEmoji('🚹', 'Men’s Room'),
    UnicodeEmoji('🚺', 'Women’s Room'),
    UnicodeEmoji('🚻', 'Restroom'),
    UnicodeEmoji('🚼', 'Baby Symbol'),
    UnicodeEmoji('🚾', 'Water Closet'),
    UnicodeEmoji('⚠️', 'Warning'),
    UnicodeEmoji('🚸', 'Children Crossing'),
    UnicodeEmoji('⛔', 'No Entry'),
    UnicodeEmoji('🚫', 'Prohibited'),
    UnicodeEmoji('🚳', 'No Bicycles'),
    UnicodeEmoji('🚭', 'No Smoking'),
    UnicodeEmoji('🚯', 'No Littering'),
    UnicodeEmoji('🚱', 'Non-Potable Water'),
    UnicodeEmoji('🚷', 'No Pedestrians'),
    UnicodeEmoji('🔞', 'No One Under Eighteen'),
    UnicodeEmoji('☢️', 'Radioactive'),
    UnicodeEmoji('☣️', 'Biohazard'),
    UnicodeEmoji('⬆️', 'Up Arrow'),
    UnicodeEmoji('↗️', 'Up-Right Arrow'),
    UnicodeEmoji('➡️', 'Right Arrow'),
    UnicodeEmoji('↘️', 'Down-Right Arrow'),
    UnicodeEmoji('⬇️', 'Down Arrow'),
    UnicodeEmoji('↙️', 'Down-Left Arrow'),
    UnicodeEmoji('⬅️', 'Left Arrow'),
    UnicodeEmoji('↖️', 'Up-Left Arrow'),
    UnicodeEmoji('↕️', 'Up-Down Arrow'),
    UnicodeEmoji('↔️', 'Left-Right Arrow'),
    UnicodeEmoji('↩️', 'Right Arrow Curving Left'),
    UnicodeEmoji('↪️', 'Left Arrow Curving Right'),
    UnicodeEmoji('⤴️', 'Right Arrow Curving Up'),
    UnicodeEmoji('⤵️', 'Right Arrow Curving Down'),
    UnicodeEmoji('🔃', 'Clockwise Vertical Arrows'),
    UnicodeEmoji('🔄', 'Counterclockwise Arrows Button'),
    UnicodeEmoji('🔙', 'Back Arrow'),
    UnicodeEmoji('🔚', 'End Arrow'),
    UnicodeEmoji('🔛', 'On! Arrow'),
    UnicodeEmoji('🔜', 'Soon Arrow'),
    UnicodeEmoji('🔝', 'Top Arrow'),
    UnicodeEmoji('🛐', 'Place of Worship'),
    UnicodeEmoji('⚛️', 'Atom Symbol'),
    UnicodeEmoji('🕉️', 'Om'),
    UnicodeEmoji('✡️', 'Star of David'),
    UnicodeEmoji('☸️', 'Wheel of Dharma'),
    UnicodeEmoji('☯️', 'Yin Yang'),
    UnicodeEmoji('✝️', 'Latin Cross'),
    UnicodeEmoji('☦️', 'Orthodox Cross'),
    UnicodeEmoji('☪️', 'Star and Crescent'),
    UnicodeEmoji('☮️', 'Peace Symbol'),
    UnicodeEmoji('🕎', 'Menorah'),
    UnicodeEmoji('🔯', 'Dotted Six-Pointed Star'),
    UnicodeEmoji('♈', 'Aries'),
    UnicodeEmoji('♉', 'Taurus'),
    UnicodeEmoji('♊', 'Gemini'),
    UnicodeEmoji('♋', 'Cancer'),
    UnicodeEmoji('♌', 'Leo'),
    UnicodeEmoji('♍', 'Virgo'),
    UnicodeEmoji('♎', 'Libra'),
    UnicodeEmoji('♏', 'Scorpio'),
    UnicodeEmoji('♐', 'Sagittarius'),
    UnicodeEmoji('♑', 'Capricorn'),
    UnicodeEmoji('♒', 'Aquarius'),
    UnicodeEmoji('♓', 'Pisces'),
    UnicodeEmoji('⛎', 'Ophiuchus'),
    UnicodeEmoji('🔀', 'Shuffle Tracks Button'),
    UnicodeEmoji('🔁', 'Repeat Button'),
    UnicodeEmoji('🔂', 'Repeat Single Button'),
    UnicodeEmoji('▶️', 'Play Button'),
    UnicodeEmoji('⏩', 'Fast-Forward Button'),
    UnicodeEmoji('◀️', 'Reverse Button'),
    UnicodeEmoji('⏪', 'Fast Reverse Button'),
    UnicodeEmoji('🔼', 'Upwards Button'),
    UnicodeEmoji('⏫', 'Fast Up Button'),
    UnicodeEmoji('🔽', 'Downwards Button'),
    UnicodeEmoji('⏬', 'Fast Down Button'),
    UnicodeEmoji('⏹️', 'Stop Button'),
    UnicodeEmoji('⏏️', 'Eject Button'),
    UnicodeEmoji('🎦', 'Cinema'),
    UnicodeEmoji('🔅', 'Dim Button'),
    UnicodeEmoji('🔆', 'Bright Button'),
    UnicodeEmoji('📶', 'Antenna Bars'),
    UnicodeEmoji('📳', 'Vibration Mode'),
    UnicodeEmoji('📴', 'Mobile Phone Off'),
    UnicodeEmoji('♾️', 'Infinity'),
    UnicodeEmoji('♻️', 'Recycling Symbol'),
    UnicodeEmoji('🔱', 'Trident Emblem'),
    UnicodeEmoji('📛', 'Name Badge'),
    UnicodeEmoji('🔰', 'Japanese Symbol for Beginner'),
    UnicodeEmoji('⭕', 'Heavy Large Circle'),
    UnicodeEmoji('✅', 'White Heavy Check Mark'),
    UnicodeEmoji('☑️', 'Ballot Box With Check'),
    UnicodeEmoji('✔️', 'Heavy Check Mark'),
    UnicodeEmoji('❌', 'Cross Mark'),
    UnicodeEmoji('❎', 'Cross Mark Button'),
    UnicodeEmoji('➕', 'Heavy Plus Sign'),
    UnicodeEmoji('➖', 'Heavy Minus Sign'),
    UnicodeEmoji('➗', 'Heavy Division Sign'),
    UnicodeEmoji('✖️', 'Heavy Multiplication X'),
    UnicodeEmoji('🟰', 'Heavy Equals Sign'),
    UnicodeEmoji('➰', 'Curly Loop'),
    UnicodeEmoji('➿', 'Double Curly Loop'),
    UnicodeEmoji('〽️', 'Part Alternation Mark'),
    UnicodeEmoji('✳️', 'Eight-Spoked Asterisk'),
    UnicodeEmoji('✴️', 'Eight-Pointed Star'),
    UnicodeEmoji('❇️', 'Sparkle'),
    UnicodeEmoji('‼️', 'Double Exclamation Mark'),
    UnicodeEmoji('⁉️', 'Exclamation Question Mark'),
    UnicodeEmoji('❓', 'Question Mark'),
    UnicodeEmoji('❔', 'White Question Mark'),
    UnicodeEmoji('❕', 'White Exclamation Mark'),
    UnicodeEmoji('❗', 'Exclamation Mark'),
    UnicodeEmoji('©️', 'Copyright'),
    UnicodeEmoji('®️', 'Registered'),
    UnicodeEmoji('™️', 'Trade Mark'),
    UnicodeEmoji('#️⃣', 'Keycap Number Sign'),
    UnicodeEmoji('0️⃣', 'Keycap Digit Zero'),
    UnicodeEmoji('1️⃣', 'Keycap Digit One'),
    UnicodeEmoji('2️⃣', 'Keycap Digit Two'),
    UnicodeEmoji('3️⃣', 'Keycap Digit Three'),
    UnicodeEmoji('4️⃣', 'Keycap Digit Four'),
    UnicodeEmoji('5️⃣', 'Keycap Digit Five'),
    UnicodeEmoji('6️⃣', 'Keycap Digit Six'),
    UnicodeEmoji('7️⃣', 'Keycap Digit Seven'),
    UnicodeEmoji('8️⃣', 'Keycap Digit Eight'),
    UnicodeEmoji('9️⃣', 'Keycap Digit Nine'),
    UnicodeEmoji('🔟', 'Keycap: 10'),
    UnicodeEmoji('🔠', 'Input Latin Uppercase'),
    UnicodeEmoji('🔡', 'Input Latin Lowercase'),
    UnicodeEmoji('🔢', 'Input Numbers'),
    UnicodeEmoji('🔣', 'Input Symbols'),
    UnicodeEmoji('🔤', 'Input Latin Letters'),
    UnicodeEmoji('🅰️', 'A Button (Blood Type)'),
    UnicodeEmoji('🆎', 'AB Button (Blood Type)'),
    UnicodeEmoji('🅱️', 'B Button (Blood Type)'),
    UnicodeEmoji('🆑', 'CL Button'),
    UnicodeEmoji('🆒', 'Cool Button'),
    UnicodeEmoji('🆓', 'Free Button'),
    UnicodeEmoji('ℹ️', 'Information'),
    UnicodeEmoji('🆔', 'ID Button'),
    UnicodeEmoji('Ⓜ️', 'Circled M'),
    UnicodeEmoji('🆕', 'New Button'),
    UnicodeEmoji('🆖', 'NG Button'),
    UnicodeEmoji('🅾️', 'O Button (Blood Type)'),
    UnicodeEmoji('🆗', 'OK Button'),
    UnicodeEmoji('🅿️', 'P Button'),
    UnicodeEmoji('🆘', 'SOS Button'),
    UnicodeEmoji('🆙', 'Up! Button'),
    UnicodeEmoji('🆚', 'Vs Button'),
    UnicodeEmoji('🈁', 'Japanese “Here” Button'),
    UnicodeEmoji('🈂️', 'Japanese “Service Charge” Button'),
    UnicodeEmoji('🈷️', 'Japanese “Monthly Amount” Button'),
    UnicodeEmoji('🈶', 'Japanese “Not Free of Charge” Button'),
    UnicodeEmoji('🈯', 'Japanese “Reserved” Button'),
    UnicodeEmoji('🉐', 'Japanese “Bargain” Button'),
    UnicodeEmoji('🈹', 'Japanese “Discount” Button'),
    UnicodeEmoji('🈚', 'Japanese “Free of Charge” Button'),
    UnicodeEmoji('🈲', 'Japanese “Prohibited” Button'),
    UnicodeEmoji('🉑', 'Japanese “Acceptable” Button'),
    UnicodeEmoji('🈸', 'Japanese “Application” Button'),
    UnicodeEmoji('🈴', 'Japanese “Passing Grade” Button'),
    UnicodeEmoji('🈳', 'Japanese “Vacancy” Button'),
    UnicodeEmoji('㊗️', 'Japanese “Congratulations” Button'),
    UnicodeEmoji('㊙️', 'Japanese “Secret” Button'),
    UnicodeEmoji('🈺', 'Japanese “Open for Business” Button'),
    UnicodeEmoji('🈵', 'Japanese “No Vacancy” Button'),
    UnicodeEmoji('🔴', 'Red Circle'),
    UnicodeEmoji('🔵', 'Blue Circle'),
    UnicodeEmoji('⚫', 'Black Circle'),
    UnicodeEmoji('⚪', 'White Circle'),
    UnicodeEmoji('⬛', 'Black Large Square'),
    UnicodeEmoji('⬜', 'White Large Square'),
    UnicodeEmoji('◼️', 'Black Medium Square'),
    UnicodeEmoji('◻️', 'White Medium Square'),
    UnicodeEmoji('◾', 'Black Medium-Small Square'),
    UnicodeEmoji('◽', 'White Medium-Small Square'),
    UnicodeEmoji('▪️', 'Black Small Square'),
    UnicodeEmoji('▫️', 'White Small Square'),
    UnicodeEmoji('🔶', 'Large Orange Diamond'),
    UnicodeEmoji('🔷', 'Large Blue Diamond'),
    UnicodeEmoji('🔸', 'Small Orange Diamond'),
    UnicodeEmoji('🔹', 'Small Blue Diamond'),
    UnicodeEmoji('🔺', 'Red Triangle Pointed Up'),
    UnicodeEmoji('🔻', 'Red Triangle Pointed Down'),
    UnicodeEmoji('💠', 'Diamond With a Dot'),
    UnicodeEmoji('🔳', 'White Square Button'),
    UnicodeEmoji('🔲', 'Black Square Button')
  ]),

// ======================================================= Category.FLAGS
  CategoryEmoji(Category.FLAGS, [
    UnicodeEmoji('🏁', 'Chequered Flag'),
    UnicodeEmoji('🚩', 'Triangular Flag'),
    UnicodeEmoji('🎌', 'Crossed Flags'),
    UnicodeEmoji('🏴', 'Black Flag'),
    UnicodeEmoji('🏳️', 'White Flag'),
    UnicodeEmoji('🏳️‍🌈', 'Rainbow Flag'),
    UnicodeEmoji('🏴‍☠️', 'Pirate Flag'),
    UnicodeEmoji('🇦🇨', 'Flag: Ascension Island'),
    UnicodeEmoji('🇦🇩', 'Flag: Andorra'),
    UnicodeEmoji('🇦🇪', 'Flag: United Arab Emirates'),
    UnicodeEmoji('🇦🇫', 'Flag: Afghanistan'),
    UnicodeEmoji('🇦🇬', 'Flag: Antigua & Barbuda'),
    UnicodeEmoji('🇦🇮', 'Flag: Anguilla'),
    UnicodeEmoji('🇦🇱', 'Flag: Albania'),
    UnicodeEmoji('🇦🇲', 'Flag: Armenia'),
    UnicodeEmoji('🇦🇴', 'Flag: Angola'),
    UnicodeEmoji('🇦🇶', 'Flag: Antarctica'),
    UnicodeEmoji('🇦🇷', 'Flag: Argentina'),
    UnicodeEmoji('🇦🇸', 'Flag: American Samoa'),
    UnicodeEmoji('🇦🇹', 'Flag: Austria'),
    UnicodeEmoji('🇦🇺', 'Flag: Australia'),
    UnicodeEmoji('🇦🇼', 'Flag: Aruba'),
    UnicodeEmoji('🇦🇽', 'Flag: Åland Islands'),
    UnicodeEmoji('🇦🇿', 'Flag: Azerbaijan'),
    UnicodeEmoji('🇧🇦', 'Flag: Bosnia & Herzegovina'),
    UnicodeEmoji('🇧🇧', 'Flag: Barbados'),
    UnicodeEmoji('🇧🇩', 'Flag: Bangladesh'),
    UnicodeEmoji('🇧🇪', 'Flag: Belgium'),
    UnicodeEmoji('🇧🇫', 'Flag: Burkina Faso'),
    UnicodeEmoji('🇧🇬', 'Flag: Bulgaria'),
    UnicodeEmoji('🇧🇭', 'Flag: Bahrain'),
    UnicodeEmoji('🇧🇮', 'Flag: Burundi'),
    UnicodeEmoji('🇧🇯', 'Flag: Benin'),
    UnicodeEmoji('🇧🇱', 'Flag: St. Barthélemy'),
    UnicodeEmoji('🇧🇲', 'Flag: Bermuda'),
    UnicodeEmoji('🇧🇳', 'Flag: Brunei'),
    UnicodeEmoji('🇧🇴', 'Flag: Bolivia'),
    UnicodeEmoji('🇧🇶', 'Flag: Caribbean Netherlands'),
    UnicodeEmoji('🇧🇷', 'Flag: Brazil'),
    UnicodeEmoji('🇧🇸', 'Flag: Bahamas'),
    UnicodeEmoji('🇧🇹', 'Flag: Bhutan'),
    UnicodeEmoji('🇧🇻', 'Flag: Bouvet Island'),
    UnicodeEmoji('🇧🇼', 'Flag: Botswana'),
    UnicodeEmoji('🇧🇾', 'Flag: Belarus'),
    UnicodeEmoji('🇧🇿', 'Flag: Belize'),
    UnicodeEmoji('🇨🇦', 'Flag: Canada'),
    UnicodeEmoji('🇨🇨', 'Flag: Cocos (Keeling) Islands'),
    UnicodeEmoji('🇨🇩', 'Flag: Congo - Kinshasa'),
    UnicodeEmoji('🇨🇫', 'Flag: Central African Republic'),
    UnicodeEmoji('🇨🇬', 'Flag: Congo - Brazzaville'),
    UnicodeEmoji('🇨🇭', 'Flag: Switzerland'),
    UnicodeEmoji('🇨🇮', 'Flag: Côte d’Ivoire'),
    UnicodeEmoji('🇨🇰', 'Flag: Cook Islands'),
    UnicodeEmoji('🇨🇱', 'Flag: Chile'),
    UnicodeEmoji('🇨🇲', 'Flag: Cameroon'),
    UnicodeEmoji('🇨🇳', 'Flag: China'),
    UnicodeEmoji('🇨🇴', 'Flag: Colombia'),
    UnicodeEmoji('🇨🇵', 'Flag: Clipperton Island'),
    UnicodeEmoji('🇨🇷', 'Flag: Costa Rica'),
    UnicodeEmoji('🇨🇺', 'Flag: Cuba'),
    UnicodeEmoji('🇨🇻', 'Flag: Cape Verde'),
    UnicodeEmoji('🇨🇼', 'Flag: Curaçao'),
    UnicodeEmoji('🇨🇽', 'Flag: Christmas Island'),
    UnicodeEmoji('🇨🇾', 'Flag: Cyprus'),
    UnicodeEmoji('🇨🇿', 'Flag: Czechia'),
    UnicodeEmoji('🇩🇪', 'Flag: Germany'),
    UnicodeEmoji('🇩🇬', 'Flag: Diego Garcia'),
    UnicodeEmoji('🇩🇯', 'Flag: Djibouti'),
    UnicodeEmoji('🇩🇰', 'Flag: Denmark'),
    UnicodeEmoji('🇩🇲', 'Flag: Dominica'),
    UnicodeEmoji('🇩🇴', 'Flag: Dominican Republic'),
    UnicodeEmoji('🇩🇿', 'Flag: Algeria'),
    UnicodeEmoji('🇪🇦', 'Flag: Ceuta & Melilla'),
    UnicodeEmoji('🇪🇨', 'Flag: Ecuador'),
    UnicodeEmoji('🇪🇪', 'Flag: Estonia'),
    UnicodeEmoji('🇪🇬', 'Flag: Egypt'),
    UnicodeEmoji('🇪🇭', 'Flag: Western Sahara'),
    UnicodeEmoji('🇪🇷', 'Flag: Eritrea'),
    UnicodeEmoji('🇪🇸', 'Flag: Spain'),
    UnicodeEmoji('🇪🇹', 'Flag: Ethiopia'),
    UnicodeEmoji('🇪🇺', 'Flag: European Union'),
    UnicodeEmoji('🇫🇮', 'Flag: Finland'),
    UnicodeEmoji('🇫🇯', 'Flag: Fiji'),
    UnicodeEmoji('🇫🇰', 'Flag: Falkland Islands'),
    UnicodeEmoji('🇫🇲', 'Flag: Micronesia'),
    UnicodeEmoji('🇫🇴', 'Flag: Faroe Islands'),
    UnicodeEmoji('🇫🇷', 'Flag: France'),
    UnicodeEmoji('🇬🇦', 'Flag: Gabon'),
    UnicodeEmoji('🇬🇧', 'Flag: United Kingdom'),
    UnicodeEmoji('🇬🇩', 'Flag: Grenada'),
    UnicodeEmoji('🇬🇪', 'Flag: Georgia'),
    UnicodeEmoji('🇬🇫', 'Flag: French Guiana'),
    UnicodeEmoji('🇬🇬', 'Flag: Guernsey'),
    UnicodeEmoji('🇬🇭', 'Flag: Ghana'),
    UnicodeEmoji('🇬🇮', 'Flag: Gibraltar'),
    UnicodeEmoji('🇬🇱', 'Flag: Greenland'),
    UnicodeEmoji('🇬🇲', 'Flag: Gambia'),
    UnicodeEmoji('🇬🇳', 'Flag: Guinea'),
    UnicodeEmoji('🇬🇵', 'Flag: Guadeloupe'),
    UnicodeEmoji('🇬🇶', 'Flag: Equatorial Guinea'),
    UnicodeEmoji('🇬🇷', 'Flag: Greece'),
    UnicodeEmoji('🇬🇸', 'Flag: South Georgia & South Sandwich Islands'),
    UnicodeEmoji('🇬🇹', 'Flag: Guatemala'),
    UnicodeEmoji('🇬🇺', 'Flag: Guam'),
    UnicodeEmoji('🇬🇼', 'Flag: Guinea-Bissau'),
    UnicodeEmoji('🇬🇾', 'Flag: Guyana'),
    UnicodeEmoji('🇭🇰', 'Flag: Hong Kong SAR China'),
    UnicodeEmoji('🇭🇲', 'Flag: Heard & McDonald Islands'),
    UnicodeEmoji('🇭🇳', 'Flag: Honduras'),
    UnicodeEmoji('🇭🇷', 'Flag: Croatia'),
    UnicodeEmoji('🇭🇹', 'Flag: Haiti'),
    UnicodeEmoji('🇭🇺', 'Flag: Hungary'),
    UnicodeEmoji('🇮🇨', 'Flag: Canary Islands'),
    UnicodeEmoji('🇮🇩', 'Flag: Indonesia'),
    UnicodeEmoji('🇮🇪', 'Flag: Ireland'),
    UnicodeEmoji('🇮🇱', 'Flag: Israel'),
    UnicodeEmoji('🇮🇲', 'Flag: Isle of Man'),
    UnicodeEmoji('🇮🇳', 'Flag: India'),
    UnicodeEmoji('🇮🇴', 'Flag: British Indian Ocean Territory'),
    UnicodeEmoji('🇮🇶', 'Flag: Iraq'),
    UnicodeEmoji('🇮🇷', 'Flag: Iran'),
    UnicodeEmoji('🇮🇸', 'Flag: Iceland'),
    UnicodeEmoji('🇮🇹', 'Flag: Italy'),
    UnicodeEmoji('🇯🇪', 'Flag: Jersey'),
    UnicodeEmoji('🇯🇲', 'Flag: Jamaica'),
    UnicodeEmoji('🇯🇴', 'Flag: Jordan'),
    UnicodeEmoji('🇯🇵', 'Flag: Japan'),
    UnicodeEmoji('🇰🇪', 'Flag: Kenya'),
    UnicodeEmoji('🇰🇬', 'Flag: Kyrgyzstan'),
    UnicodeEmoji('🇰🇭', 'Flag: Cambodia'),
    UnicodeEmoji('🇰🇮', 'Flag: Kiribati'),
    UnicodeEmoji('🇰🇲', 'Flag: Comoros'),
    UnicodeEmoji('🇰🇳', 'Flag: St. Kitts & Nevis'),
    UnicodeEmoji('🇰🇵', 'Flag: North Korea'),
    UnicodeEmoji('🇰🇷', 'Flag: South Korea'),
    UnicodeEmoji('🇰🇼', 'Flag: Kuwait'),
    UnicodeEmoji('🇰🇾', 'Flag: Cayman Islands'),
    UnicodeEmoji('🇰🇿', 'Flag: Kazakhstan'),
    UnicodeEmoji('🇱🇦', 'Flag: Laos'),
    UnicodeEmoji('🇱🇧', 'Flag: Lebanon'),
    UnicodeEmoji('🇱🇨', 'Flag: St. Lucia'),
    UnicodeEmoji('🇱🇮', 'Flag: Liechtenstein'),
    UnicodeEmoji('🇱🇰', 'Flag: Sri Lanka'),
    UnicodeEmoji('🇱🇷', 'Flag: Liberia'),
    UnicodeEmoji('🇱🇸', 'Flag: Lesotho'),
    UnicodeEmoji('🇱🇹', 'Flag: Lithuania'),
    UnicodeEmoji('🇱🇺', 'Flag: Luxembourg'),
    UnicodeEmoji('🇱🇻', 'Flag: Latvia'),
    UnicodeEmoji('🇱🇾', 'Flag: Libya'),
    UnicodeEmoji('🇲🇦', 'Flag: Morocco'),
    UnicodeEmoji('🇲🇨', 'Flag: Monaco'),
    UnicodeEmoji('🇲🇩', 'Flag: Moldova'),
    UnicodeEmoji('🇲🇪', 'Flag: Montenegro'),
    UnicodeEmoji('🇲🇫', 'Flag: St. Martin'),
    UnicodeEmoji('🇲🇬', 'Flag: Madagascar'),
    UnicodeEmoji('🇲🇭', 'Flag: Marshall Islands'),
    UnicodeEmoji('🇲🇰', 'Flag: North Macedonia'),
    UnicodeEmoji('🇲🇱', 'Flag: Mali'),
    UnicodeEmoji('🇲🇲', 'Flag: Myanmar (Burma)'),
    UnicodeEmoji('🇲🇳', 'Flag: Mongolia'),
    UnicodeEmoji('🇲🇴', 'Flag: Macau Sar China'),
    UnicodeEmoji('🇲🇵', 'Flag: Northern Mariana Islands'),
    UnicodeEmoji('🇲🇶', 'Flag: Martinique'),
    UnicodeEmoji('🇲🇷', 'Flag: Mauritania'),
    UnicodeEmoji('🇲🇸', 'Flag: Montserrat'),
    UnicodeEmoji('🇲🇹', 'Flag: Malta'),
    UnicodeEmoji('🇲🇺', 'Flag: Mauritius'),
    UnicodeEmoji('🇲🇻', 'Flag: Maldives'),
    UnicodeEmoji('🇲🇼', 'Flag: Malawi'),
    UnicodeEmoji('🇲🇽', 'Flag: Mexico'),
    UnicodeEmoji('🇲🇾', 'Flag: Malaysia'),
    UnicodeEmoji('🇲🇿', 'Flag: Mozambique'),
    UnicodeEmoji('🇳🇦', 'Flag: Namibia'),
    UnicodeEmoji('🇳🇨', 'Flag: New Caledonia'),
    UnicodeEmoji('🇳🇪', 'Flag: Niger'),
    UnicodeEmoji('🇳🇫', 'Flag: Norfolk Island'),
    UnicodeEmoji('🇳🇬', 'Flag: Nigeria'),
    UnicodeEmoji('🇳🇮', 'Flag: Nicaragua'),
    UnicodeEmoji('🇳🇱', 'Flag: Netherlands'),
    UnicodeEmoji('🇳🇴', 'Flag: Norway'),
    UnicodeEmoji('🇳🇵', 'Flag: Nepal'),
    UnicodeEmoji('🇳🇷', 'Flag: Nauru'),
    UnicodeEmoji('🇳🇺', 'Flag: Niue'),
    UnicodeEmoji('🇳🇿', 'Flag: New Zealand'),
    UnicodeEmoji('🇴🇲', 'Flag: Oman'),
    UnicodeEmoji('🇵🇦', 'Flag: Panama'),
    UnicodeEmoji('🇵🇪', 'Flag: Peru'),
    UnicodeEmoji('🇵🇫', 'Flag: French Polynesia'),
    UnicodeEmoji('🇵🇬', 'Flag: Papua New Guinea'),
    UnicodeEmoji('🇵🇭', 'Flag: Philippines'),
    UnicodeEmoji('🇵🇰', 'Flag: Pakistan'),
    UnicodeEmoji('🇵🇱', 'Flag: Poland'),
    UnicodeEmoji('🇵🇲', 'Flag: St. Pierre & Miquelon'),
    UnicodeEmoji('🇵🇳', 'Flag: Pitcairn Islands'),
    UnicodeEmoji('🇵🇷', 'Flag: Puerto Rico'),
    UnicodeEmoji('🇵🇸', 'Flag: Palestinian Territories'),
    UnicodeEmoji('🇵🇹', 'Flag: Portugal'),
    UnicodeEmoji('🇵🇼', 'Flag: Palau'),
    UnicodeEmoji('🇵🇾', 'Flag: Paraguay'),
    UnicodeEmoji('🇶🇦', 'Flag: Qatar'),
    UnicodeEmoji('🇷🇪', 'Flag: Réunion'),
    UnicodeEmoji('🇷🇴', 'Flag: Romania'),
    UnicodeEmoji('🇷🇸', 'Flag: Serbia'),
    UnicodeEmoji('🇷🇺', 'Flag: Russia'),
    UnicodeEmoji('🇷🇼', 'Flag: Rwanda'),
    UnicodeEmoji('🇸🇦', 'Flag: Saudi Arabia'),
    UnicodeEmoji('🇸🇧', 'Flag: Solomon Islands'),
    UnicodeEmoji('🇸🇨', 'Flag: Seychelles'),
    UnicodeEmoji('🇸🇩', 'Flag: Sudan'),
    UnicodeEmoji('🇸🇪', 'Flag: Sweden'),
    UnicodeEmoji('🇸🇬', 'Flag: Singapore'),
    UnicodeEmoji('🇸🇭', 'Flag: St. Helena'),
    UnicodeEmoji('🇸🇮', 'Flag: Slovenia'),
    UnicodeEmoji('🇸🇯', 'Flag: Svalbard & Jan Mayen'),
    UnicodeEmoji('🇸🇰', 'Flag: Slovakia'),
    UnicodeEmoji('🇸🇱', 'Flag: Sierra Leone'),
    UnicodeEmoji('🇸🇲', 'Flag: San Marino'),
    UnicodeEmoji('🇸🇳', 'Flag: Senegal'),
    UnicodeEmoji('🇸🇴', 'Flag: Somalia'),
    UnicodeEmoji('🇸🇷', 'Flag: Suriname'),
    UnicodeEmoji('🇸🇸', 'Flag: South Sudan'),
    UnicodeEmoji('🇸🇹', 'Flag: São Tomé & Príncipe'),
    UnicodeEmoji('🇸🇻', 'Flag: El Salvador'),
    UnicodeEmoji('🇸🇽', 'Flag: Sint Maarten'),
    UnicodeEmoji('🇸🇾', 'Flag: Syria'),
    UnicodeEmoji('🇸🇿', 'Flag: Swaziland'),
    UnicodeEmoji('🇹🇦', 'Flag: Tristan Da Cunha'),
    UnicodeEmoji('🇹🇨', 'Flag: Turks & Caicos Islands'),
    UnicodeEmoji('🇹🇩', 'Flag: Chad'),
    UnicodeEmoji('🇹🇫', 'Flag: French Southern Territories'),
    UnicodeEmoji('🇹🇬', 'Flag: Togo'),
    UnicodeEmoji('🇹🇭', 'Flag: Thailand'),
    UnicodeEmoji('🇹🇯', 'Flag: Tajikistan'),
    UnicodeEmoji('🇹🇰', 'Flag: Tokelau'),
    UnicodeEmoji('🇹🇱', 'Flag: Timor-Leste'),
    UnicodeEmoji('🇹🇲', 'Flag: Turkmenistan'),
    UnicodeEmoji('🇹🇳', 'Flag: Tunisia'),
    UnicodeEmoji('🇹🇴', 'Flag: Tonga'),
    UnicodeEmoji('🇹🇷', 'Flag: Turkey'),
    UnicodeEmoji('🇹🇹', 'Flag: Trinidad & Tobago'),
    UnicodeEmoji('🇹🇻', 'Flag: Tuvalu'),
    UnicodeEmoji('🇹🇼', 'Flag: Taiwan'),
    UnicodeEmoji('🇹🇿', 'Flag: Tanzania'),
    UnicodeEmoji('🇺🇦', 'Flag: Ukraine'),
    UnicodeEmoji('🇺🇬', 'Flag: Uganda'),
    UnicodeEmoji('🇺🇲', 'Flag: U.S. Outlying Islands'),
    UnicodeEmoji('🇺🇳', 'Flag: United Nations'),
    UnicodeEmoji('🇺🇸', 'Flag: United States'),
    UnicodeEmoji('🇺🇾', 'Flag: Uruguay'),
    UnicodeEmoji('🇺🇿', 'Flag: Uzbekistan'),
    UnicodeEmoji('🇻🇦', 'Flag: Vatican City'),
    UnicodeEmoji('🇻🇨', 'Flag: St. Vincent & Grenadines'),
    UnicodeEmoji('🇻🇪', 'Flag: Venezuela'),
    UnicodeEmoji('🇻🇬', 'Flag: British Virgin Islands'),
    UnicodeEmoji('🇻🇮', 'Flag: U.S. Virgin Islands'),
    UnicodeEmoji('🇻🇳', 'Flag: Vietnam'),
    UnicodeEmoji('🇻🇺', 'Flag: Vanuatu'),
    UnicodeEmoji('🇼🇫', 'Flag: Wallis & Futuna'),
    UnicodeEmoji('🇼🇸', 'Flag: Samoa'),
    UnicodeEmoji('🇽🇰', 'Flag: Kosovo'),
    UnicodeEmoji('🇾🇪', 'Flag: Yemen'),
    UnicodeEmoji('🇾🇹', 'Flag: Mayotte'),
    UnicodeEmoji('🇿🇦', 'Flag: South Africa'),
    UnicodeEmoji('🇿🇲', 'Flag: Zambia'),
    UnicodeEmoji('🇿🇼', 'Flag: Zimbabwe')
  ]),
];
